import jsPDF from 'jspdf'

export interface LCBConsentInput {
  lrNumber: string
  parcelNumber: string
  county: string
  division: string
  district: string
  areaHa: number
  landUse: string
  transferorName: string
  transfereeName: string
  transferorIdNumber?: string
  transfereeIdNumber?: string
  surveyorName: string
  iskNumber: string
  surveyDate: string
  referenceNumber: string
  lbcApplicationNumber?: string
}

export function generateLCBConsent(input: LCBConsentInput): Uint8Array {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = 210
  const margin = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('LAND CONTROL ACT (CAP 302)', W / 2, 22, { align: 'center' })
  doc.setFontSize(11)
  doc.text('LAND CONTROL BOARD — CONSENT APPLICATION', W / 2, 30, { align: 'center' })

  doc.setLineWidth(0.5)
  doc.line(margin, 35, W - margin, 35)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(`Reference: ${input.referenceNumber}`, margin, 42)
  if (input.lbcApplicationNumber) {
    doc.text(`LCB Application No.: ${input.lbcApplicationNumber}`, W - margin, 42, { align: 'right' })
  }
  doc.text(`Date: ${new Date(input.surveyDate).toLocaleDateString('en-GB')}`, W - margin, 49, { align: 'right' })

  let y = 52
  const lineH = 8

  function sectionHeader(title: string) {
    doc.setFillColor(27, 58, 92)
    doc.rect(margin, y, W - margin * 2, 7, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(255, 255, 255)
    doc.text(title, margin + 3, y + 5)
    doc.setTextColor(0, 0, 0)
    y += 10
  }

  function field(label: string, value: string) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.text(value || '—', margin + 50, y)
    doc.setLineWidth(0.1)
    doc.line(margin + 50, y + 1, W - margin, y + 1)
    y += lineH
  }

  sectionHeader('LAND DETAILS')
  field('LR Number:', input.lrNumber)
  field('Parcel Number:', input.parcelNumber)
  field('County:', input.county)
  field('Division:', input.division)
  field('District:', input.district)
  field('Area (Ha):', input.areaHa.toFixed(4))
  field('Land Use:', input.landUse)
  y += 4

  sectionHeader('PARTIES TO THE TRANSACTION')
  field('Transferor (Owner):', input.transferorName)
  field('Transferor ID / PIN:', input.transferorIdNumber ?? '')
  field('Transferee (Applicant):', input.transfereeName)
  field('Transferee ID / PIN:', input.transfereeIdNumber ?? '')
  y += 4

  sectionHeader('LICENSED SURVEYOR DETAILS')
  field('Surveyor Name:', input.surveyorName)
  field('ISK Number:', input.iskNumber)
  field('Survey Date:', new Date(input.surveyDate).toLocaleDateString('en-GB'))
  y += 4

  sectionHeader('APPLICATION STATEMENT')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  const statement = [
    `We, the undersigned, hereby apply to the Land Control Board, ${input.county} County,`,
    `for consent to the transaction described above concerning land parcel ${input.parcelNumber}`,
    `(LR ${input.lrNumber}) situated in ${input.division}, ${input.district}.`,
    '',
    'We declare that the information provided is true and accurate, and we submit to the',
    'jurisdiction of the Land Control Board as required under the Land Control Act Cap 302.',
  ]
  statement.forEach(line => {
    doc.text(line, margin, y)
    y += 6
  })
  y += 8

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8.5)

  doc.text('Transferor Signature:', margin, y)
  doc.line(margin + 42, y + 1, margin + 95, y + 1)
  doc.text('Date:', margin + 105, y)
  doc.line(margin + 115, y + 1, W - margin, y + 1)
  y += 14

  doc.text('Transferee Signature:', margin, y)
  doc.line(margin + 42, y + 1, margin + 95, y + 1)
  doc.text('Date:', margin + 105, y)
  doc.line(margin + 115, y + 1, W - margin, y + 1)
  y += 14

  doc.text('Surveyor Signature:', margin, y)
  doc.line(margin + 42, y + 1, margin + 95, y + 1)
  doc.text('Date:', margin + 105, y)
  doc.line(margin + 115, y + 1, W - margin, y + 1)
  y += 14

  doc.setFillColor(240, 244, 248)
  doc.rect(margin, y, W - margin * 2, 28, 'F')
  doc.setLineWidth(0.3)
  doc.rect(margin, y, W - margin * 2, 28)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8.5)
  doc.text('FOR LAND CONTROL BOARD OFFICE USE ONLY', margin + 3, y + 6)
  doc.setFont('helvetica', 'normal')
  doc.text('Consent Granted / Refused (circle):  GRANTED     /     REFUSED', margin + 3, y + 14)
  doc.text('Board Chairman Signature: _________________________', margin + 3, y + 22)
  doc.text(`Date: _______________`, margin + 130, y + 22)

  doc.setFont('helvetica', 'italic')
  doc.setFontSize(7.5)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by Metardu Survey Platform — Land Control Act Cap 302 Compliant', W / 2, 285, { align: 'center' })

  return doc.output('arraybuffer') as unknown as Uint8Array
}