import jsPDF from 'jspdf'

export interface PPA2Input {
  lrNumber: string
  parcelNumber: string
  county: string
  division: string
  district: string
  locality: string
  areaHa: number
  surveyType: string
  applicantName: string
  applicantAddress: string
  applicantIdNumber?: string
  surveyorName: string
  iskNumber: string
  firmName: string
  surveyDate: string
  referenceNumber: string
}

export function generatePPA2Form(input: PPA2Input): Uint8Array {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = 210
  const margin = 20

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(13)
  doc.text('PHYSICAL PLANNING ACT (CAP 286)', W / 2, 22, { align: 'center' })
  doc.setFontSize(11)
  doc.text('FORM 2 — APPLICATION FOR DEVELOPMENT PERMISSION', W / 2, 30, { align: 'center' })
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text('(Regulation 4)', W / 2, 37, { align: 'center' })

  doc.setLineWidth(0.5)
  doc.line(margin, 41, W - margin, 41)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.text(`Reference No.: ${input.referenceNumber}`, margin, 48)
  doc.text(`Date: ${new Date(input.surveyDate).toLocaleDateString('en-GB')}`, W - margin, 48, { align: 'right' })

  let y = 56
  const lineH = 8

  function sectionHeader(title: string) {
    doc.setFillColor(27, 58, 92)
    doc.rect(margin, y, W - margin * 2, 7, 'F')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(9)
    doc.setTextColor(255, 255, 255)
    doc.text(title, margin + 3, y + 5)
    doc.setTextColor(0, 0, 0)
    y += 10
  }

  function field(label: string, value: string) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(8.5)
    doc.text(label, margin, y)
    doc.setFont('helvetica', 'normal')
    doc.text(value || '—', margin + 55, y)
    doc.setLineWidth(0.1)
    doc.line(margin + 55, y + 1, W - margin, y + 1)
    y += lineH
  }

  sectionHeader('PART A — LAND DETAILS')
  field('LR Number:', input.lrNumber)
  field('Parcel Number:', input.parcelNumber)
  field('County:', input.county)
  field('Division:', input.division)
  field('District:', input.district)
  field('Locality / Town:', input.locality)
  field('Area (Ha):', input.areaHa.toFixed(4))
  field('Nature of Survey:', input.surveyType)
  y += 4

  sectionHeader('PART B — APPLICANT DETAILS')
  field('Full Name:', input.applicantName)
  field('Postal Address:', input.applicantAddress)
  field('ID / PIN Number:', input.applicantIdNumber ?? '')
  y += 4

  sectionHeader('PART C — LICENSED SURVEYOR')
  field('Surveyor Name:', input.surveyorName)
  field('ISK Number:', input.iskNumber)
  field('Firm / Company:', input.firmName)
  field('Survey Date:', new Date(input.surveyDate).toLocaleDateString('en-GB'))
  y += 4

  sectionHeader('PART D — DECLARATION')
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8.5)
  const declaration = [
    'I/We hereby apply for permission to carry out the development described above.',
    'I/We declare that the information given in this form is true and correct to the best of my/our knowledge.',
    'I/We understand that it is an offence under Section 30 of the Physical Planning Act to carry out',
    'development without permission.',
  ]
  declaration.forEach(line => {
    doc.text(line, margin, y)
    y += 6
  })
  y += 6

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(8.5)
  doc.text('Applicant Signature:', margin, y)
  doc.line(margin + 40, y + 1, margin + 100, y + 1)
  doc.text('Date:', margin + 110, y)
  doc.line(margin + 122, y + 1, W - margin, y + 1)
  y += 14

  doc.text('Surveyor Signature:', margin, y)
  doc.line(margin + 40, y + 1, margin + 100, y + 1)
  doc.text('Date:', margin + 110, y)
  doc.line(margin + 122, y + 1, W - margin, y + 1)
  y += 14

  doc.setFont('helvetica', 'italic')
  doc.setFontSize(7.5)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by Metardu Survey Platform — Kenya Survey Regulations 1994 Compliant', W / 2, 285, { align: 'center' })

  return doc.output('arraybuffer') as unknown as Uint8Array
}