/**
 * Kenya Topo Sheet Data — loaded from JSON
 *
 * ponytail: Phase 8 — was a 3,819 LOC .ts file with pure data. Converted to
 * JSON (122 KB) and loaded via import. The .ts file is deleted; the JSON is
 * the source of truth. Regenerated by: npm run cassini:rebuild
 */

import type { TopoSheetParams } from './cassini'
// ponytail: moved to data/cassini/ — was 3,819 LOC of inline TS data in src/
import kenyaSheetsData from '../../../data/cassini/kenya_sheets.json'

export const ALL_KENYA_SHEETS: TopoSheetParams[] = kenyaSheetsData as TopoSheetParams[]
