/**
 * Civil Engineering Data Handoff
 * Packages survey data for direct use in AutoCAD Civil 3D, 12d, QGIS, ArcGIS.
 * No extra computation — formats data from the existing project.
 */

import { utmToGeographic } from '@/lib/geodesy/coordinates'

export interface CivilPoint {
  name: string
  easting: number
  northing: number
  elevation: number
  is_control: boolean
  code?: string
}

export interface AlignmentPoint {
  chainage: number
  easting: number
  northing: number
  elevation: number
}

// ── CSV for Civil 3D point import (PENZD format) ─────────────────────────────
// Civil 3D reads: Point#,Easting,Northing,Elevation,Description
export function exportCivil3DCSV(points: CivilPoint[], projectName: string): string {
  const lines = [
    `# Civil 3D Point Import — ${projectName}`,
    `# Generated by METARDU | Format: PENZD`,
    `# Point No.,Easting(m),Northing(m),Elevation(m),Description`,
  ]
  points.forEach((p, i) => {
    const desc = p.is_control ? `CTRL-${p.name}` : p.code || `SURV-${p.name}`
    lines.push(`${i + 1},${p.easting.toFixed(4)},${p.northing.toFixed(4)},${p.elevation.toFixed(4)},${desc}`)
  })
  return lines.join('\n')
}

// ── 12d Model CSV format ──────────────────────────────────────────────────────
// 12d reads: Name,Easting,Northing,RL,String
export function export12dCSV(points: CivilPoint[], projectName: string): string {
  const lines = [
    `! 12d Model Survey Data — ${projectName}`,
    `! Generated by METARDU`,
    `! Name,Easting,Northing,RL,String`,
  ]
  points.forEach((p: any) => {
    const str = p.is_control ? 'CTRL' : 'SURV'
    lines.push(`${p.name},${p.easting.toFixed(4)},${p.northing.toFixed(4)},${p.elevation.toFixed(4)},${str}`)
  })
  return lines.join('\n')
}

// ── MOSS / Microdrainage DEF format ──────────────────────────────────────────
export function exportMossDEF(points: CivilPoint[]): string {
  const lines = ['MOSS Survey Points', 'BEGIN DATA']
  points.forEach((p: any) => {
    lines.push(`${p.easting.toFixed(3)} ${p.northing.toFixed(3)} ${p.elevation.toFixed(3)} ${p.name}`)
  })
  lines.push('END DATA')
  return lines.join('\n')
}

// ── LAS-style ASCII point cloud (for topo surveys) ───────────────────────────
// Can be opened in CloudCompare, Recap, Civil 3D
export function exportASCIIPointCloud(points: CivilPoint[]): string {
  const lines = ['//X Y Z Intensity Name']
  points.forEach((p: any) => {
    const intensity = p.is_control ? 65535 : 32767
    lines.push(`${p.easting.toFixed(4)} ${p.northing.toFixed(4)} ${p.elevation.toFixed(4)} ${intensity} ${p.name}`)
  })
  return lines.join('\n')
}

// ── Shapefile-ready CSV (ESRI-compatible) ────────────────────────────────────
export function exportShapefileCSV(points: CivilPoint[], utmZone: number, hemisphere: 'N'|'S'): string {
  const lines = ['Name,Easting,Northing,Elevation,Lat_WGS84,Lon_WGS84,Type,UTM_Zone']
  points.forEach((p: any) => {
    const { lat, lon } = utmToGeographic(p.easting, p.northing, utmZone, hemisphere)
    lines.push([
      p.name,
      p.easting.toFixed(4),
      p.northing.toFixed(4),
      p.elevation.toFixed(4),
      lat.toFixed(8),
      lon.toFixed(8),
      p.is_control ? 'Control' : 'Survey',
      `${utmZone}${hemisphere}`,
    ].join(','))
  })
  return lines.join('\n')
}

// ── LandXML with surface (for Civil 3D / InfraWorks) ─────────────────────────
export function exportLandXMLSurface(
  points: CivilPoint[],
  projectName: string,
  utmZone: number,
  hemisphere: 'N' | 'S'
): string {
  const date = new Date().toISOString()
  const epsg = hemisphere === 'S' ? 32700 + utmZone : 32600 + utmZone

  const cgPoints = points.map((p, i) =>
    `      <CgPoint name="${p.name}" pntRef="${i+1}">${p.northing.toFixed(4)} ${p.easting.toFixed(4)} ${p.elevation.toFixed(4)}</CgPoint>`
  ).join('\n')

  const pntList = points.map((_, i) => i + 1).join(' ')

  return `<?xml version="1.0" encoding="UTF-8"?>
<LandXML xmlns="http://www.landxml.org/schema/LandXML-1.2"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.landxml.org/schema/LandXML-1.2 http://www.landxml.org/schema/LandXML1.2/LandXML1.2.xsd"
  date="${date.split('T')[0]}" time="${date.split('T')[1].split('.')[0]}"
  version="1.2" language="English" readOnly="false">
  <Project name="${projectName}" />
  <CoordinateSystem name="UTM_Zone_${utmZone}${hemisphere}" epsgCode="${epsg}"
    datum="WGS84" horizontalDatum="WGS84" verticalDatum="MSL" />
  <Units>
    <Metric linearUnit="meter" areaUnit="squareMeter" volumeUnit="cubicMeter" />
  </Units>
  <CgPoints>
${cgPoints}
  </CgPoints>
  <Surfaces>
    <Surface name="${projectName} — Existing Ground" desc="Survey surface for Civil 3D">
      <SourceData>
        <PntList3D>${pntList}</PntList3D>
      </SourceData>
    </Surface>
  </Surfaces>
</LandXML>`
}

export type CivilFormat = 'civil3d' | '12d' | 'moss' | 'pointcloud' | 'shapefile_csv' | 'landxml_surface'

export const CIVIL_FORMATS: { id: CivilFormat; label: string; software: string; ext: string; desc: string }[] = [
  { id: 'civil3d',        label: 'Civil 3D PENZD',      software: 'AutoCAD Civil 3D',            ext: 'csv',  desc: 'Direct import into Civil 3D via Points → Import Points → PENZD' },
  { id: '12d',            label: '12d Model CSV',        software: '12d Model',                   ext: 'csv',  desc: 'Import as 12d survey string data' },
  { id: 'moss',           label: 'MOSS / Microdrainage', software: 'MOSS, Microdrainage',         ext: 'def',  desc: 'ASCII point format for MOSS and drainage software' },
  { id: 'pointcloud',     label: 'ASCII Point Cloud',    software: 'CloudCompare, ReCap, Civil 3D',ext: 'txt', desc: 'X Y Z intensity — opens in CloudCompare and Autodesk ReCap' },
  { id: 'shapefile_csv',  label: 'Shapefile CSV',        software: 'QGIS, ArcGIS, MapInfo',       ext: 'csv',  desc: 'CSV with WGS84 lat/lon — import as shapefile in QGIS or ArcGIS' },
  { id: 'landxml_surface',label: 'LandXML Surface',      software: 'Civil 3D, InfraWorks, 12d',  ext: 'xml',  desc: 'Existing ground surface for design and volume calculations' },
]

export function exportCivil(
  points: CivilPoint[],
  format: CivilFormat,
  projectName: string,
  utmZone: number,
  hemisphere: 'N' | 'S'
): { content: string; ext: string } {
  const fmt = CIVIL_FORMATS.find((f: any) => f.id === format)!
  switch (format) {
    case 'civil3d':         return { content: exportCivil3DCSV(points, projectName),             ext: fmt.ext }
    case '12d':             return { content: export12dCSV(points, projectName),                  ext: fmt.ext }
    case 'moss':            return { content: exportMossDEF(points),                              ext: fmt.ext }
    case 'pointcloud':      return { content: exportASCIIPointCloud(points),                      ext: fmt.ext }
    case 'shapefile_csv':   return { content: exportShapefileCSV(points, utmZone, hemisphere),    ext: fmt.ext }
    case 'landxml_surface': return { content: exportLandXMLSurface(points, projectName, utmZone, hemisphere), ext: fmt.ext }
    default:                return { content: exportCivil3DCSV(points, projectName),             ext: 'csv' }
  }
}
