/**
 * @module realTimeQC
 *
 * Real-time quality control for survey observations.
 *
 * Catches errors DURING data collection, not after. Previously, a surveyor
 * could spend an entire day in the field only to discover at the end that
 * the traverse doesn't close. This module surfaces problems as they happen.
 *
 * Features:
 *   1. Running closure monitor — shows live misclosure as each leg is added
 *   2. Redundant observation detection — flags same leg measured twice with diff values
 *   3. Setup verification — checks instrument height, target height, temp/pressure
 *   4. Outlier detection — Chauvenet's criterion for statistical outlier rejection
 *   5. Real-time precision indicator — running 1:N ratio as traverse progresses
 *
 * References:
 *   - "Elementary Surveying" by Ghilani & Wolf, 16th Ed., Chapter 3 (errors)
 *   - Chauvenet's criterion: reject if probability < 1/(2n)
 *   - RDM 1.1 (2025) — Kenya tolerance limits
 */

import type { Point2D } from '@/lib/engine/types'

// ─── 1. Running Closure Monitor ─────────────────────────────────────────────

export interface RunningClosureState {
  /** Number of legs observed so far */
  legCount: number
  /** Cumulative easting misclosure (sum of ΔE) */
  cumulativeDE: number
  /** Cumulative northing misclosure (sum of ΔN) */
  cumulativeDN: number
  /** Linear misclosure (sqrt(ΔE² + ΔN²)) */
  linearMisclosure: number
  /** Total distance traversed so far */
  totalDistance: number
  /** Running precision ratio (1:N) — 0 if no distance yet */
  precisionRatio: number | null
  /** Precision ratio as a string ("1:5000") or null */
  precisionLabel: string | null
  /** Whether the current precision meets the minimum standard */
  meetsStandard: boolean
  /** The minimum precision ratio required (based on survey class) */
  minRequired: number
  /** Warnings generated by this leg */
  warnings: string[]
}

export type SurveyClass = 'urban' | 'rural' | 'topographic' | 'control'

const PRECISION_STANDARDS: Record<SurveyClass, number> = {
  urban: 10000,      // 1:10,000
  rural: 5000,       // 1:5,000
  topographic: 1000, // 1:1,000
  control: 20000,    // 1:20,000
}

/**
 * Track the running closure of a traverse as legs are added.
 * Call addLeg() for each new observation. The state updates live.
 */
export class RunningClosureMonitor {
  private legs: Array<{ dE: number; dN: number; distance: number }> = []
  private surveyClass: SurveyClass

  constructor(surveyClass: SurveyClass = 'urban') {
    this.surveyClass = surveyClass
  }

  setSurveyClass(cls: SurveyClass) {
    this.surveyClass = cls
  }

  /**
   * Add a traverse leg (bearing + distance → ΔE, ΔN).
   * Returns the updated closure state.
   */
  addLeg(bearingDeg: number, distance: number): RunningClosureState {
    const bearingRad = (bearingDeg * Math.PI) / 180
    const dE = distance * Math.sin(bearingRad)
    const dN = distance * Math.cos(bearingRad)

    this.legs.push({ dE, dN, distance })

    return this.getState()
  }

  /**
   * Add a leg from raw coordinate differences (for GNSS observations).
   */
  addLegFromCoords(dE: number, dN: number): RunningClosureState {
    const distance = Math.sqrt(dE * dE + dN * dN)
    this.legs.push({ dE, dN, distance })
    return this.getState()
  }

  /** Remove the last leg (undo). */
  removeLastLeg(): RunningClosureState {
    this.legs.pop()
    return this.getState()
  }

  /** Clear all legs. */
  reset() {
    this.legs = []
  }

  /** Get the current closure state. */
  getState(): RunningClosureState {
    const cumulativeDE = this.legs.reduce((s, l) => s + l.dE, 0)
    const cumulativeDN = this.legs.reduce((s, l) => s + l.dN, 0)
    const linearMisclosure = Math.sqrt(cumulativeDE ** 2 + cumulativeDN ** 2)
    const totalDistance = this.legs.reduce((s, l) => s + l.distance, 0)
    const minRequired = PRECISION_STANDARDS[this.surveyClass]

    const precisionRatio = totalDistance > 0 && linearMisclosure > 0
      ? Math.round(totalDistance / linearMisclosure)
      : totalDistance > 0 ? Infinity : 0

    const meetsStandard = precisionRatio >= minRequired
    const precisionLabel = precisionRatio === Infinity
      ? '1:∞ (perfect so far)'
      : precisionRatio > 0 ? `1:${precisionRatio}` : null

    // Generate warnings
    const warnings: string[] = []
    if (this.legs.length >= 3 && !meetsStandard && precisionRatio !== Infinity) {
      warnings.push(
        `Precision ${precisionLabel} is below ${this.surveyClass} standard (1:${minRequired}). ` +
        `Current misclosure: ${linearMisclosure.toFixed(3)}m over ${totalDistance.toFixed(1)}m.`
      )
    }
    if (this.legs.length >= 2 && linearMisclosure > 0.05 && totalDistance < 500) {
      warnings.push(
        `Early misclosure of ${linearMisclosure.toFixed(3)}m detected after only ${this.legs.length} legs. ` +
        `Check the first setup for instrument/target height errors.`
      )
    }

    return {
      legCount: this.legs.length,
      cumulativeDE,
      cumulativeDN,
      linearMisclosure,
      totalDistance,
      precisionRatio: precisionRatio === Infinity ? null : precisionRatio,
      precisionLabel,
      meetsStandard,
      minRequired,
      warnings,
    }
  }
}

// ─── 2. Redundant Observation Detection ─────────────────────────────────────

export interface Observation {
  fromStation: string
  toStation: string
  bearing?: number  // decimal degrees
  distance?: number // metres
  timestamp?: string
}

export interface RedundantObservationResult {
  /** The pair of observations that disagree */
  observations: [Observation, Observation]
  /** Bearing difference in seconds of arc (if both have bearings) */
  bearingDifferenceSec: number | null
  /** Distance difference in mm (if both have distances) */
  distanceDifferenceMm: number | null
  /** Whether the difference exceeds tolerance */
  exceedsTolerance: boolean
  /** Severity: 'error' if > 2× tolerance, 'warn' if > tolerance */
  severity: 'error' | 'warn'
  /** Human-readable message */
  message: string
}

/**
 * Detect redundant observations (same leg measured twice) and check
 * if they agree within tolerance.
 *
 * @param observations All observations in the survey
 * @param bearingToleranceSec Bearing tolerance in arcseconds (default: 30")
 * @param distanceToleranceMm Distance tolerance in mm (default: 10mm)
 * @returns Array of disagreements (empty if all redundant observations agree)
 */
export function detectRedundantObservationDiscrepancies(
  observations: Observation[],
  bearingToleranceSec: number = 30,
  distanceToleranceMm: number = 10,
): RedundantObservationResult[] {
  const results: RedundantObservationResult[] = []

  // Group observations by (from, to) pair
  const groups = new Map<string, Observation[]>()

  for (const obs of observations) {
    const key = `${obs.fromStation}->${obs.toStation}`
    const reverseKey = `${obs.toStation}->${obs.fromStation}`

    // Check if we already have observations for this leg (either direction)
    if (groups.has(key)) {
      groups.get(key)!.push(obs)
    } else if (groups.has(reverseKey)) {
      groups.get(reverseKey)!.push(obs)
    } else {
      groups.set(key, [obs])
    }
  }

  // Check each group with 2+ observations
  for (const [, group] of groups) {
    if (group.length < 2) continue

    for (let i = 0; i < group.length; i++) {
      for (let j = i + 1; j < group.length; j++) {
        const obs1 = group[i]
        const obs2 = group[j]

        let bearingDiffSec: number | null = null
        let distanceDiffMm: number | null = null
        let exceeds = false
        let severity: 'error' | 'warn' = 'warn'

        // Bearing check
        if (obs1.bearing != null && obs2.bearing != null) {
          // For reverse directions, add 180°
          let b1 = obs1.bearing
          let b2 = obs2.bearing
          if (obs1.fromStation !== obs2.fromStation) {
            b2 = (b2 + 180) % 360 // reverse the second bearing
          }
          let diff = Math.abs(b1 - b2)
          if (diff > 180) diff = 360 - diff
          bearingDiffSec = diff * 3600
          if (bearingDiffSec > bearingToleranceSec) {
            exceeds = true
            severity = bearingDiffSec > bearingToleranceSec * 2 ? 'error' : 'warn'
          }
        }

        // Distance check
        if (obs1.distance != null && obs2.distance != null) {
          distanceDiffMm = Math.abs(obs1.distance - obs2.distance) * 1000
          if (distanceDiffMm > distanceToleranceMm) {
            exceeds = true
            severity = distanceDiffMm > distanceToleranceMm * 2 ? 'error' : 'warn'
          }
        }

        if (exceeds) {
          const parts: string[] = []
          if (bearingDiffSec != null) {
            parts.push(`bearing diff ${bearingDiffSec.toFixed(1)}" (tol ${bearingToleranceSec}")`)
          }
          if (distanceDiffMm != null) {
            parts.push(`distance diff ${distanceDiffMm.toFixed(1)}mm (tol ${distanceToleranceMm}mm)`)
          }

          results.push({
            observations: [obs1, obs2],
            bearingDifferenceSec: bearingDiffSec,
            distanceDifferenceMm: distanceDiffMm,
            exceedsTolerance: true,
            severity,
            message: `Redundant observation discrepancy on ${obs1.fromStation}→${obs1.toStation}: ${parts.join(', ')}`,
          })
        }
      }
    }
  }

  return results
}

// ─── 3. Setup Verification ──────────────────────────────────────────────────

export interface SetupCheck {
  field: string
  value: number | null
  expected: string
  passed: boolean
  message: string
}

/**
 * Verify a setup before taking observations.
 * Catches common field mistakes: forgotten instrument height, wrong
 * temperature/pressure units, etc.
 */
export function verifySetup(input: {
  instrumentHeight?: number
  targetHeight?: number
  temperature?: number  // Celsius
  pressure?: number     // hPa/mbar
  isControlPoint?: boolean
}): SetupCheck[] {
  const checks: SetupCheck[] = []

  // Instrument height
  checks.push({
    field: 'instrumentHeight',
    value: input.instrumentHeight ?? null,
    expected: '1.0–2.0 m',
    passed: input.instrumentHeight != null && input.instrumentHeight >= 0.5 && input.instrumentHeight <= 3.0,
    message: input.instrumentHeight == null
      ? 'Instrument height not entered — EDM correction will be wrong'
      : input.instrumentHeight < 0.5
        ? `Instrument height ${input.instrumentHeight}m is unusually low — check measurement`
        : input.instrumentHeight > 3.0
          ? `Instrument height ${input.instrumentHeight}m is unusually high — check measurement`
          : `Instrument height ${input.instrumentHeight}m is within normal range`,
  })

  // Target height
  checks.push({
    field: 'targetHeight',
    value: input.targetHeight ?? null,
    expected: '1.0–2.5 m',
    passed: input.targetHeight != null && input.targetHeight >= 0.3 && input.targetHeight <= 3.5,
    message: input.targetHeight == null
      ? 'Target/prism height not entered — EDM correction will be wrong'
      : input.targetHeight < 0.3
        ? `Target height ${input.targetHeight}m is unusually low`
        : input.targetHeight > 3.5
          ? `Target height ${input.targetHeight}m is unusually high`
          : `Target height ${input.targetHeight}m is within normal range`,
  })

  // Temperature
  if (input.temperature != null) {
    checks.push({
      field: 'temperature',
      value: input.temperature,
      expected: '10–45 °C (Kenya range)',
      passed: input.temperature >= 5 && input.temperature <= 50,
      message: input.temperature < 5
        ? `Temperature ${input.temperature}°C is below Kenya range — check unit (Fahrenheit vs Celsius?)`
        : input.temperature > 50
          ? `Temperature ${input.temperature}°C is above Kenya range — check unit`
          : `Temperature ${input.temperature}°C is normal`,
    })
  }

  // Pressure
  if (input.pressure != null) {
    checks.push({
      field: 'pressure',
      value: input.pressure,
      expected: '700–1050 hPa (sea level to 3000m)',
      passed: input.pressure >= 600 && input.pressure <= 1100,
      message: input.pressure < 600
        ? `Pressure ${input.pressure}hPa is too low — check unit (inHg vs hPa?)`
        : input.pressure > 1100
          ? `Pressure ${input.pressure}hPa is too high — check unit`
          : `Pressure ${input.pressure}hPa is normal`,
    })
  }

  // Control point check
  if (input.isControlPoint) {
    checks.push({
      field: 'isControlPoint',
      value: 1,
      expected: 'verified control point',
      passed: true,
      message: 'Set up on a control point — good practice',
    })
  }

  return checks
}

// ─── 4. Outlier Detection (Chauvenet's Criterion) ──────────────────────────

/**
 * Detect statistical outliers in a set of repeated measurements using
 * Chauvenet's criterion.
 *
 * A measurement is rejected if the probability of its deviation from
 * the mean is less than 1/(2n), where n is the number of measurements.
 *
 * @param values Array of measured values (e.g., repeated distances)
 * @returns Indices of rejected outliers, or empty array if none
 */
export function detectOutliers(values: number[]): {
  outliers: number[]
  mean: number
  stdDev: number
  details: Array<{ index: number; value: number; deviation: number; criticalValue: number; rejected: boolean }>
} {
  const n = values.length
  if (n < 3) {
    return { outliers: [], mean: 0, stdDev: 0, details: [] }
  }

  // Calculate mean
  const mean = values.reduce((s, v) => s + v, 0) / n

  // Calculate standard deviation (sample)
  const variance = values.reduce((s, v) => s + (v - mean) ** 2, 0) / (n - 1)
  const stdDev = Math.sqrt(variance)

  if (stdDev === 0) {
    return { outliers: [], mean, stdDev: 0, details: [] }
  }

  // Chauvenet's critical value: reject if |deviation| / stdDev > t_critical
  // where t_critical corresponds to probability 1 - 1/(2n)
  // For small n, use the t-distribution approximation
  // t_critical ≈ inverse_normal_cdf(1 - 1/(4n))
  const criticalProb = 1 - 1 / (4 * n)
  const tCritical = inverseNormalCdf(criticalProb)

  const details = values.map((value, index) => {
    const deviation = Math.abs(value - mean)
    const tStat = deviation / stdDev
    const rejected = tStat > tCritical
    return { index, value, deviation, criticalValue: tCritical, rejected }
  })

  const outliers = details.filter(d => d.rejected).map(d => d.index)

  return { outliers, mean, stdDev, details }
}

/**
 * Approximation of the inverse normal CDF (probit function).
 * Uses Acklam's algorithm.
 */
function inverseNormalCdf(p: number): number {
  const a = [-3.969683028665376e+01, 2.209460984245205e+02, -2.759285104469687e+02, 1.383577518672690e+02, -3.066479806614716e+01, 2.506628277459239e+00]
  const b = [-5.447609879822406e+01, 1.615858368580409e+02, -1.556989798598866e+02, 6.680131188771972e+01, -1.328068155288572e+01]
  const c = [-7.784894002430293e-03, -3.223964580411365e-01, -2.400758277161838e+00, -2.549732539343734e+00, 4.374664141464968e+00, 2.938163982698783e+00]
  const d = [7.784695709041462e-03, 3.224671290700398e-01, 2.445134137142996e+00, 3.754408661907416e+00]

  const pLow = 0.02425
  const pHigh = 1 - pLow

  if (p < pLow) {
    const q = Math.sqrt(-2 * Math.log(p))
    return (((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) /
           ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1)
  } else if (p <= pHigh) {
    const q = p - 0.5
    const r = q * q
    return (((((a[0] * r + a[1]) * r + a[2]) * r + a[3]) * r + a[4]) * r + a[5]) * q /
           (((((b[0] * r + b[1]) * r + b[2]) * r + b[3]) * r + b[4]) * r + 1)
  } else {
    const q = Math.sqrt(-2 * Math.log(1 - p))
    return -(((((c[0] * q + c[1]) * q + c[2]) * q + c[3]) * q + c[4]) * q + c[5]) /
            ((((d[0] * q + d[1]) * q + d[2]) * q + d[3]) * q + 1)
  }
}

// ─── 5. Real-Time Precision Indicator ───────────────────────────────────────

/**
 * Format a precision ratio for display.
 * @param ratio The 1:N ratio (e.g., 5000 for 1:5000)
 * @param surveyClass The survey class for comparison
 * @returns Formatted string with compliance status
 */
export function formatPrecisionIndicator(
  ratio: number | null,
  surveyClass: SurveyClass = 'urban',
): { label: string; compliant: boolean; color: string } {
  if (ratio === null) {
    return { label: '—', compliant: true, color: 'gray' }
  }

  const minRequired = PRECISION_STANDARDS[surveyClass]
  const compliant = ratio >= minRequired

  let color: string
  if (compliant) {
    color = 'green'
  } else if (ratio >= minRequired * 0.5) {
    color = 'amber'
  } else {
    color = 'red'
  }

  return {
    label: `1:${ratio.toLocaleString()}`,
    compliant,
    color,
  }
}
