import { SurveyType } from '@/types/project';
import { SubmissionDocument } from '@/types/submission';

export const SUBMISSION_DOCUMENTS: SubmissionDocument[] = [
  {
    id: 'traverse-report',
    label: 'Traverse Computation Report',
    description: 'Bowditch-adjusted traverse with angular and linear closure.',
    format: 'pdf',
    surveyTypes: ['cadastral', 'engineering', 'topographic', 'geodetic'],
    requiredData: ['traverse observations', 'starting coordinates'],
  },
  {
    id: 'field-book',
    label: 'Field Book Workbook',
    description: 'Complete field observations in spreadsheet format.',
    format: 'xlsx',
    surveyTypes: [
      'cadastral', 'engineering', 'topographic', 'geodetic',
      'drone', 'deformation',
    ],
    requiredData: ['field book entries'],
  },
  {
    id: 'levelling-report',
    label: 'Levelling Report',
    description: 'Rise & fall / HPC reduction with 10√K mm closure check per RDM 1.1 Table 5.1.',
    format: 'pdf',
    surveyTypes: ['engineering', 'topographic', 'geodetic', 'deformation'],
    requiredData: ['levelling observations', 'benchmark RL'],
  },
  {
    id: 'working-diagram',
    label: 'Working Diagram',
    description: 'Scaled traverse diagram with beacon annotations.',
    format: 'pdf',
    surveyTypes: ['cadastral', 'engineering', 'topographic'],
    requiredData: ['adjusted traverse coordinates', 'beacon data'],
  },
  {
    id: 'deed-plan',
    label: 'Deed Plan (Form No. 4)',
    description: 'Regulatory cadastral plan per Survey Act Cap 299.',
    format: 'pdf',
    surveyTypes: ['cadastral'],
    requiredData: ['adjusted coordinates', 'beacon data', 'LR number', 'client details'],
  },
  {
    id: 'boundary-shapefile',
    label: 'Boundary Shapefile',
    description: 'Parcel boundary as zipped shapefile for GIS use.',
    format: 'shp',
    surveyTypes: ['cadastral'],
    requiredData: ['adjusted coordinates'],
  },
  {
    id: 'setting-out-dxf',
    label: 'Setting-Out DXF',
    description: 'Setting-out data in DXF format for AutoCAD import.',
    format: 'dxf',
    surveyTypes: ['engineering'],
    requiredData: ['setting-out observations', 'design coordinates'],
  },
  {
    id: 'longitudinal-section',
    label: 'Longitudinal Section Report',
    description: 'Profile levels along centreline with RL and chainage.',
    format: 'pdf',
    surveyTypes: ['engineering', 'topographic'],
    requiredData: ['longitudinal section data'],
  },
  {
    id: 'volumetric-report',
    label: 'Volumetric / Earthworks Report',
    description: 'Cut and fill volumes with prismoidal correction.',
    format: 'pdf',
    surveyTypes: ['engineering', 'drone'],
    requiredData: ['cross-section data or point cloud', 'design surface'],
  },
  {
    id: 'gcp-report',
    label: 'GCP Accuracy Report',
    description: 'Ground control point residuals and overall accuracy certificate.',
    format: 'pdf',
    surveyTypes: ['drone'],
    requiredData: ['GCP coordinates', 'photogrammetry report'],
  },
  {
    id: 'orthophoto-plan',
    label: 'Orthophoto Plan',
    description: 'Orthophoto evidence sheet with parcel boundary and encroachment overlays, exported as PDF.',
    format: 'pdf',
    surveyTypes: ['drone'],
    requiredData: ['orthophoto image or imagery overlay', 'parcel boundary', 'project extent'],
  },
  {
    id: 'deformation-report',
    label: 'Deformation / Monitoring Report',
    description: 'Epoch comparison with displacement vectors and statistical analysis.',
    format: 'pdf',
    surveyTypes: ['deformation'],
    requiredData: ['epoch observations', 'reference epoch'],
  },
  {
    id: 'control-schedule',
    label: 'Coordinate Schedule',
    description: 'Final adjusted coordinates of all control points.',
    format: 'xlsx',
    surveyTypes: ['geodetic', 'cadastral', 'engineering'],
    requiredData: ['adjusted coordinates'],
  },
  {
    id: 'rim',
    label: 'RIM (Resurvey and Index Map)',
    description: 'Resurvey and Index Map for cadastral registration per Survey Act Cap 299.',
    format: 'pdf',
    surveyTypes: ['cadastral'],
    requiredData: ['adjusted coordinates', 'beacon data', 'LR number'],
  },
  {
    id: 'form-c22',
    label: 'Form C22 — Computation Sheet',
    description: 'Official DoLS computation sheet with observed bearings, traverse adjustment, area computation, and closure summary per Survey Regulations 1994.',
    format: 'pdf',
    surveyTypes: ['cadastral'],
    requiredData: ['adjusted coordinates', 'bearing schedule', 'surveyor details'],
  },
  {
    id: 'area-computation',
    label: 'Area Computation Sheet',
    description: 'Standalone area computation using Shoelace formula with verification section.',
    format: 'pdf',
    surveyTypes: ['cadastral'],
    requiredData: ['adjusted coordinates', 'surveyor details'],
  },
  {
    id: 'traverse-computation-sheet',
    label: 'Traverse Computation Sheet',
    description: 'Full traverse computation sheet with reduced observations (HCL/HCR in DMS), Bowditch adjustment, final coordinate schedule, and closure summary per RDM 1.1 Table 2.4.',
    format: 'pdf',
    surveyTypes: ['cadastral', 'engineering', 'geodetic'],
    requiredData: ['traverse observations', 'adjusted coordinates', 'surveyor details'],
  },
  {
    id: 'mutation-form',
    label: 'Survey Mutation Form',
    description: 'Mutation form with parent parcel, resulting parcels, affected beacons, and surveyor certification per Survey Regulations 1994.',
    format: 'pdf',
    surveyTypes: ['cadastral'],
    requiredData: ['parent parcel data', 'resulting parcels', 'beacon data', 'surveyor details'],
  },
  {
    id: 'full-package',
    label: 'Full Submission Package',
    description: 'All completed documents bundled as a single ZIP.',
    format: 'zip',
    surveyTypes: [
      'cadastral', 'engineering', 'topographic', 'geodetic',
      'drone', 'deformation',
    ],
    requiredData: ['all documents above must be generated first'],
  },
];

export function getDocumentsForSurveyType(surveyType: string): SubmissionDocument[] {
  return SUBMISSION_DOCUMENTS.filter((doc) =>
    doc.surveyTypes.includes(surveyType as SurveyType)
  );
}
