/**
 * Statutory Forms Generator — Form P + Topo Surveyor's Report + Cross-Section Sheets
 *
 * Three additional statutory documents for Kenyan surveyors, complementing the
 * consolidated Survey Report:
 *
 *   1. FORM P — MUTATION FORM
 *      Per Survey Act Cap 299, Survey Regulations 1994 Reg 38.
 *      Used for subdivision, amalgamation, or boundary adjustment of
 *      registered land. Submitted to Director of Surveys for approval.
 *
 *   2. SURVEYOR'S REPORT (TOPOGRAPHICAL)
 *      Per Survey of Kenya Practice Notes 2020.
 *      Narrative report describing the survey methodology, equipment,
 *      control network, accuracy achieved, and deliverables for a
 *      topographical survey.
 *
 *   3. CROSS-SECTION SHEETS (ENGINEERING)
 *      Per Road Design Manual RDM 1.1 (2025), Section 6.
 *      Tabular cross-sections at each chainage along an alignment,
 *      showing existing ground, design level, cut/fill depths, areas,
 *      and cumulative volumes. Used for earthworks verification and
 *      payment certification.
 *
 * All three forms are sealed with RSA-2048 (reusing crypto-seal.ts).
 * Output: Vector PDF, A4 portrait.
 */

import PDFDocument from 'pdfkit';
import * as fs from 'node:fs';
import * as path from 'node:path';
import log from 'electron-log/main';
import { sealDocument, loadOrCreateSurveyorKeypair, type SurveyorKeypair } from './crypto-seal.js';

// ─── Constants ─────────────────────────────────────────────────────────
const MM_TO_PT = 2.8346;
const A4_WIDTH_PT = 210 * MM_TO_PT;
const A4_HEIGHT_PT = 297 * MM_TO_PT;
const MARGIN_PT = 15 * MM_TO_PT;

const COLOR_BLACK = '#000000';
const COLOR_GREY = '#666666';
const COLOR_LIGHT_GREY = '#CCCCCC';
const COLOR_ACCENT = '#003366';
const COLOR_WARNING = '#CC0000';
const COLOR_BLUE = '#0066CC';
const COLOR_GREEN = '#008800';

const FS_TITLE = 14;
const FS_HEADING = 11;
const FS_SUBHEADING = 9;
const FS_BODY = 8;
const FS_SMALL = 6.5;

// ─── Shared Types ──────────────────────────────────────────────────────

interface CommonSurveyor {
  name: string;
  license: string;
  firmName?: string;
  postalAddress?: string;
  phoneNumber?: string;
  email?: string;
}

interface CommonProject {
  name: string;
  parcelNumber: string;
  lrNumber: string;
  county: string;
  subCounty?: string;
  locality: string;
  surveyDate: string;
  projection: string;
  datum: string;
  zone?: string;
  directorOfSurveysRef?: string;
}

interface SealInfo {
  signature: string;
  publicKeyPem: string;
  keyFingerprint: string;
  signedAt: string;
  documentHash: string;
}

interface FormResult {
  pdfPath: string;
  pdfSizeBytes: number;
  pageCount: number;
  sealed: boolean;
  signatureFingerprint?: string;
  signedAt?: string;
  warnings: string[];
}

// ─── Shared Helpers ────────────────────────────────────────────────────

function drawHeader(doc: PDFKit.PDFDocument, project: CommonProject, pageNum: string, title: string) {
  const top = MARGIN_PT;
  doc.moveTo(MARGIN_PT, top + 18)
    .lineTo(A4_WIDTH_PT - MARGIN_PT, top + 18)
    .lineWidth(1.2)
    .stroke(COLOR_ACCENT);

  doc.font('Helvetica-Bold')
    .fontSize(FS_HEADING)
    .fillColor(COLOR_ACCENT)
    .text('REPUBLIC OF KENYA — SURVEY OF KENYA', MARGIN_PT, top);

  doc.font('Helvetica')
    .fontSize(FS_SUBHEADING)
    .fillColor(COLOR_BLACK)
    .text(title, MARGIN_PT, top + 12);

  doc.font('Helvetica')
    .fontSize(FS_SUBHEADING)
    .fillColor(COLOR_GREY)
    .text(`Page ${pageNum}`, A4_WIDTH_PT - 80, top, { width: 65, align: 'right' });
}

function drawFooter(doc: PDFKit.PDFDocument, project: CommonProject, surveyor: CommonSurveyor) {
  const bottom = A4_HEIGHT_PT - MARGIN_PT - 14;
  doc.moveTo(MARGIN_PT, bottom)
    .lineTo(A4_WIDTH_PT - MARGIN_PT, bottom)
    .lineWidth(0.5)
    .stroke(COLOR_GREY);

  doc.font('Helvetica')
    .fontSize(FS_SMALL)
    .fillColor(COLOR_GREY)
    .text(
      `Surveyor: ${surveyor.name} (Lic. ${surveyor.license})  •  Parcel: ${project.parcelNumber}  •  LR: ${project.lrNumber}  •  Generated by METARDU Desktop`,
      MARGIN_PT,
      bottom + 3,
      { width: A4_WIDTH_PT - 2 * MARGIN_PT, align: 'center' }
    );
}

function fmtCoord(v: number): string { return v.toFixed(3); }
function fmtDistance(v: number): string { return v.toFixed(3); }
function fmtArea(v: number): string {
  return v.toLocaleString('en-KE', { minimumFractionDigits: 3, maximumFractionDigits: 3 });
}
function sqMToHa(v: number): number { return v / 10000; }
function sqMToAcres(v: number): number { return v / 4046.8564224; }

async function sealAndAppendCertificate(
  basePath: string,
  surveyor: CommonSurveyor,
  project: CommonProject,
  drawCertPage: (doc: PDFKit.PDFDocument, seal: SealInfo) => void,
  sealWithRSA: boolean,
  keypair?: SurveyorKeypair,
): Promise<{ sealed: boolean; fingerprint?: string; signedAt?: string; warnings: string[] }> {
  const warnings: string[] = [];
  const pdfBytes = fs.readFileSync(basePath);
  const crypto = await import('node:crypto');
  const documentHash = crypto.createHash('sha256').update(pdfBytes).digest('hex');

  let sealed = false;
  let fingerprint: string | undefined;
  let signedAt: string | undefined;

  if (sealWithRSA !== false) {
    try {
      const kp = keypair ?? loadOrCreateSurveyorKeypair();
      const seal = sealDocument(documentHash, kp);
      sealed = true;
      fingerprint = seal.keyFingerprint;
      signedAt = seal.signedAt;

      const sealInfo: SealInfo = {
        signature: seal.signature,
        publicKeyPem: seal.publicKeyPem,
        keyFingerprint: seal.keyFingerprint,
        signedAt: seal.signedAt,
        documentHash,
      };

      const certDoc = new PDFDocument({
        size: [A4_WIDTH_PT, A4_HEIGHT_PT],
        margins: { top: MARGIN_PT, bottom: MARGIN_PT, left: MARGIN_PT, right: MARGIN_PT },
      });
      const tmpPath = basePath + '.cert.tmp';
      const stream = fs.createWriteStream(tmpPath);
      certDoc.pipe(stream);

      drawHeader(certDoc, project, 'Cert', "Surveyor's Certificate");
      drawCertPage(certDoc, sealInfo);

      // Digital seal block
      drawDigitalSealBlock(certDoc, sealInfo);

      drawFooter(certDoc, project, surveyor);
      certDoc.end();

      await new Promise<void>((resolve, reject) => {
        stream.on('finish', () => resolve());
        stream.on('error', reject);
      });

      // Merge using pdf-lib (aliased to avoid name collision with PDFKit's PDFDocument)
      const pdfLib = await import('pdf-lib');
      const basePdf = await pdfLib.PDFDocument.load(fs.readFileSync(basePath));
      const certPdf = await pdfLib.PDFDocument.load(fs.readFileSync(tmpPath));
      const copiedPages = await basePdf.copyPages(certPdf, certPdf.getPageIndices());
      for (const p of copiedPages) basePdf.addPage(p);
      const mergedBytes = await basePdf.save();
      fs.writeFileSync(basePath, mergedBytes);
      fs.unlinkSync(tmpPath);
    } catch (err) {
      log.error('RSA sealing failed: ' + String(err));
      warnings.push(`RSA sealing failed: ${String(err)}`);
    }
  }

  return { sealed, fingerprint, signedAt, warnings };
}

function drawDigitalSealBlock(doc: PDFKit.PDFDocument, seal: SealInfo) {
  let y = A4_HEIGHT_PT - MARGIN_PT - 110;

  doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_ACCENT);
  y += 8;

  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('Digital Seal (RSA-2048)', MARGIN_PT, y);
  y += 16;

  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text('This document is digitally sealed with RSA-SHA256. Verification:', MARGIN_PT, y);
  y += 14;

  const labelW = 50 * MM_TO_PT;
  const sealRows: Array<[string, string]> = [
    ['Algorithm', 'RSA-SHA256 (RSA-2048 keypair)'],
    ['Signed at', seal.signedAt],
    ['Document hash (SHA-256)', seal.documentHash],
    ['Key fingerprint', seal.keyFingerprint],
    ['Public key', seal.publicKeyPem.split('\n').slice(0, 2).join(' ') + ' …'],
    ['Signature (base64)', seal.signature.substring(0, 64) + ' …'],
  ];
  for (const [label, value] of sealRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Courier').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: A4_WIDTH_PT - MARGIN_PT - labelW });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
  }
}

// ══════════════════════════════════════════════════════════════════════
// FORM P — MUTATION FORM (Subdivision / Amalgamation / Boundary Adjustment)
// ══════════════════════════════════════════════════════════════════════

export type MutationType = 'subdivision' | 'amalgamation' | 'boundary_adjustment';

export interface FormPInput {
  project: CommonProject & {
    mutationType: MutationType;
    registry: string;          // e.g. 'Kiambu'
    originalGrant?: string;    // original grant number
    titleNumber?: string;      // title deed number
  };
  surveyor: CommonSurveyor;
  parentParcel: {
    parcelNumber: string;
    lrNumber: string;
    registry: string;
    titleNumber?: string;
    areaSqM: number;
    perimeter: number;
    ownerName?: string;
    ownerPno?: string;
    pointCount: number;
    beaconCount: number;
  };
  newParcels: Array<{
    parcelNumber: string;
    areaSqM: number;
    perimeter: number;
    pointCount: number;
    beaconCount: number;
    purpose?: string;          // e.g. 'Residential', 'Commercial'
    proposedOwner?: string;
    proposedOwnerPno?: string;
  }>;
  extinguishedBeacons: Array<{
    number: string;
    reason: string;            // e.g. 'Subsumed into new parcel boundary'
  }>;
  newBeacons: Array<{
    number: string;
    type: 'concrete' | 'iron_pin' | 'stone' | 'reference_object';
    easting: number;
    northing: number;
    description?: string;
  }>;
  balanceArea?: {
    areaSqM: number;
    purpose: string;            // e.g. 'Access road', 'Open space'
  };
  outputPath: string;
  sealWithRSA?: boolean;
  keypair?: SurveyorKeypair;
}

export async function generateFormP(input: FormPInput): Promise<FormResult> {
  log.info(`Generating Form P (mutation) for parcel ${input.project.parcelNumber}`);

  const warnings: string[] = [];
  if (input.newParcels.length === 0) {
    warnings.push('No new parcels specified — mutation form will be empty.');
  }
  const sumNew = input.newParcels.reduce((s, p) => s + p.areaSqM, 0);
  const balance = input.balanceArea?.areaSqM ?? (input.parentParcel.areaSqM - sumNew);
  const delta = input.parentParcel.areaSqM - sumNew - balance;
  if (Math.abs(delta) > 0.01) {
    warnings.push(`Area reconciliation delta ${delta.toFixed(3)} m² exceeds tolerance.`);
  }

  const doc = new PDFDocument({
    size: [A4_WIDTH_PT, A4_HEIGHT_PT],
    margins: { top: MARGIN_PT, bottom: MARGIN_PT, left: MARGIN_PT, right: MARGIN_PT },
    info: {
      Title: `Form P — Mutation — ${input.project.parcelNumber}`,
      Author: `${input.surveyor.name} (Lic. ${input.surveyor.license})`,
      Subject: `Mutation: ${input.project.mutationType}`,
      Keywords: 'Survey of Kenya, Cap 299, Reg 38, Mutation, METARDU Desktop',
      Producer: 'METARDU Desktop',
    },
  });

  const stream = fs.createWriteStream(input.outputPath);
  doc.pipe(stream);

  // ─── Page 1: Mutation Header + Parent Parcel ──────────────────────
  drawHeader(doc, input.project, '1', 'FORM P — MUTATION FORM (Reg 38)');

  let y = MARGIN_PT + 30;
  doc.font('Helvetica-Bold')
    .fontSize(FS_TITLE + 2)
    .fillColor(COLOR_ACCENT)
    .text('FORM P', MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 22;
  const mutationTitle = input.project.mutationType === 'subdivision' ? 'APPLICATION FOR SUBDIVISION'
    : input.project.mutationType === 'amalgamation' ? 'APPLICATION FOR AMALGAMATION'
    : 'APPLICATION FOR BOUNDARY ADJUSTMENT';

  doc.font('Helvetica-Bold')
    .fontSize(FS_HEADING)
    .fillColor(COLOR_BLACK)
    .text(mutationTitle, MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 18;
  doc.font('Helvetica-Oblique')
    .fontSize(FS_SUBHEADING)
    .fillColor(COLOR_GREY)
    .text('Survey Act (Cap. 299), Survey Regulations 1994 — Regulation 38',
      MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  // Application details table
  y += 22;
  const labelW = 50 * MM_TO_PT;
  const valW = (A4_WIDTH_PT - 2 * MARGIN_PT) - labelW;

  const appRows: Array<[string, string]> = [
    ['Mutation Type', input.project.mutationType.replace('_', ' ').toUpperCase()],
    ['Registry', input.project.registry],
    ['Original Grant', input.project.originalGrant ?? '—'],
    ['Title Number', input.project.titleNumber ?? input.parentParcel.titleNumber ?? '—'],
    ['County', input.project.county],
    ['Sub-County', input.project.subCounty ?? '—'],
    ['Locality', input.project.locality],
    ['Survey Date', input.project.surveyDate],
    ['Projection', input.project.projection],
    ['Datum', input.project.datum],
    ['Director of Surveys Ref.', input.project.directorOfSurveysRef ?? '—'],
    ['Applicant Surveyor', `${input.surveyor.name} (Lic. ${input.surveyor.license})`],
    ['Surveyor Firm', input.surveyor.firmName ?? '—'],
  ];

  for (const [label, value] of appRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12)
      .lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  // Parent parcel block
  y += 10;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('PARENT PARCEL (Existing)', MARGIN_PT, y);
  y += 16;

  const parentRows: Array<[string, string]> = [
    ['Parcel Number', input.parentParcel.parcelNumber],
    ['LR Number', input.parentParcel.lrNumber],
    ['Registry', input.parentParcel.registry],
    ['Title Number', input.parentParcel.titleNumber ?? '—'],
    ['Area (m²)', fmtArea(input.parentParcel.areaSqM)],
    ['Area (ha)', sqMToHa(input.parentParcel.areaSqM).toFixed(4)],
    ['Area (acres)', sqMToAcres(input.parentParcel.areaSqM).toFixed(4)],
    ['Perimeter (m)', fmtDistance(input.parentParcel.perimeter)],
    ['Point Count', String(input.parentParcel.pointCount)],
    ['Beacon Count', String(input.parentParcel.beaconCount)],
    ['Current Owner', input.parentParcel.ownerName ?? '—'],
    ['Owner P/No', input.parentParcel.ownerPno ?? '—'],
  ];

  for (const [label, value] of parentRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12)
      .lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  drawFooter(doc, input.project, input.surveyor);

  // ─── Page 2: New Parcels Schedule ─────────────────────────────────
  doc.addPage();
  drawHeader(doc, input.project, '2', 'FORM P — NEW PARCELS SCHEDULE');
  y = MARGIN_PT + 30;

  doc.font('Helvetica-Bold')
    .fontSize(FS_TITLE)
    .fillColor(COLOR_ACCENT)
    .text('SCHEDULE OF NEW PARCELS', MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 18;
  doc.font('Helvetica-Oblique')
    .fontSize(FS_SUBHEADING)
    .fillColor(COLOR_GREY)
    .text(`Total new parcels created: ${input.newParcels.length}`, MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 22;
  // Table header
  const cols = [
    { title: '#', x: MARGIN_PT, w: 8 * MM_TO_PT, align: 'left' as const },
    { title: 'New Parcel No.', x: MARGIN_PT + 8 * MM_TO_PT, w: 28 * MM_TO_PT, align: 'left' as const },
    { title: 'Area (m²)', x: MARGIN_PT + 36 * MM_TO_PT, w: 22 * MM_TO_PT, align: 'right' as const },
    { title: 'Area (ha)', x: MARGIN_PT + 58 * MM_TO_PT, w: 22 * MM_TO_PT, align: 'right' as const },
    { title: 'Perim. (m)', x: MARGIN_PT + 80 * MM_TO_PT, w: 22 * MM_TO_PT, align: 'right' as const },
    { title: 'Pts', x: MARGIN_PT + 102 * MM_TO_PT, w: 12 * MM_TO_PT, align: 'right' as const },
    { title: 'Bcn', x: MARGIN_PT + 114 * MM_TO_PT, w: 12 * MM_TO_PT, align: 'right' as const },
    { title: 'Purpose', x: MARGIN_PT + 126 * MM_TO_PT, w: 30 * MM_TO_PT, align: 'left' as const },
    { title: 'Proposed Owner', x: MARGIN_PT + 156 * MM_TO_PT, w: 39 * MM_TO_PT, align: 'left' as const },
  ];

  for (const c of cols) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(c.title, c.x, y, { width: c.w, align: c.align });
  }
  y += 12;
  doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);

  for (let i = 0; i < input.newParcels.length; i++) {
    const p = input.newParcels[i];
    y += 2;
    const rowY = y;
    doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(String(i + 1), cols[0].x, rowY, { width: cols[0].w, align: 'left' });
    doc.font('Helvetica-Bold').fontSize(FS_SMALL)
      .text(p.parcelNumber, cols[1].x, rowY, { width: cols[1].w, align: 'left' });
    doc.font('Courier').fontSize(FS_SMALL)
      .text(fmtArea(p.areaSqM), cols[2].x, rowY, { width: cols[2].w, align: 'right' });
    doc.text(sqMToHa(p.areaSqM).toFixed(4), cols[3].x, rowY, { width: cols[3].w, align: 'right' });
    doc.text(fmtDistance(p.perimeter), cols[4].x, rowY, { width: cols[4].w, align: 'right' });
    doc.font('Helvetica').fontSize(FS_SMALL)
      .text(String(p.pointCount), cols[5].x, rowY, { width: cols[5].w, align: 'right' })
      .text(String(p.beaconCount), cols[6].x, rowY, { width: cols[6].w, align: 'right' })
      .text(p.purpose ?? '—', cols[7].x, rowY, { width: cols[7].w, align: 'left' });
    doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_GREY)
      .text(p.proposedOwner ?? '—', cols[8].x, rowY, { width: cols[8].w, align: 'left' });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);

    if (y > A4_HEIGHT_PT - MARGIN_PT - 30) {
      doc.addPage();
      drawHeader(doc, input.project, '2 (cont.)', 'FORM P — NEW PARCELS SCHEDULE');
      y = MARGIN_PT + 30;
      for (const c of cols) {
        doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
          .text(c.title, c.x, y, { width: c.w, align: c.align });
      }
      y += 12;
      doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);
    }
  }

  // Totals row
  y += 8;
  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text('TOTALS', MARGIN_PT, y, { width: 36 * MM_TO_PT });
  const totalArea = input.newParcels.reduce((s, p) => s + p.areaSqM, 0);
  const totalPerim = input.newParcels.reduce((s, p) => s + p.perimeter, 0);
  const totalPts = input.newParcels.reduce((s, p) => s + p.pointCount, 0);
  const totalBcn = input.newParcels.reduce((s, p) => s + p.beaconCount, 0);
  doc.font('Courier').fontSize(FS_BODY)
    .text(fmtArea(totalArea), cols[2].x, y, { width: cols[2].w, align: 'right' })
    .text(sqMToHa(totalArea).toFixed(4), cols[3].x, y, { width: cols[3].w, align: 'right' })
    .text(fmtDistance(totalPerim), cols[4].x, y, { width: cols[4].w, align: 'right' });
  doc.font('Helvetica-Bold').fontSize(FS_BODY)
    .text(String(totalPts), cols[5].x, y, { width: cols[5].w, align: 'right' })
    .text(String(totalBcn), cols[6].x, y, { width: cols[6].w, align: 'right' });

  // Reconciliation
  y += 20;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('AREA RECONCILIATION', MARGIN_PT, y);
  y += 16;

  const reconRows: Array<[string, string, string]> = [
    ['Parent parcel area', fmtArea(input.parentParcel.areaSqM) + ' m²', ''],
    ['Sum of new parcels', fmtArea(totalArea) + ' m²', ''],
    ['Balance (roads/open space)', fmtArea(balance) + ' m²', input.balanceArea?.purpose ?? '—'],
    ['Reconciliation delta', fmtArea(Math.abs(delta)) + ' m²', Math.abs(delta) < 0.01 ? 'OK' : 'CHECK'],
    ['Result', Math.abs(delta) < 0.01 ? 'PASS' : 'FAIL', Math.abs(delta) < 0.01 ? '' : 'Investigate delta'],
  ];
  for (const [label, value, status] of reconRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Courier').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.font('Helvetica-Bold').fontSize(FS_BODY)
      .fillColor(status === 'OK' || status === 'PASS' ? COLOR_BLACK : status === 'CHECK' || status === 'FAIL' ? COLOR_WARNING : COLOR_GREY)
      .text(status, MARGIN_PT + labelW + valW, y, { width: 30 * MM_TO_PT });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  drawFooter(doc, input.project, input.surveyor);

  // ─── Page 3: Beacons Affected ────────────────────────────────────
  doc.addPage();
  drawHeader(doc, input.project, '3', 'FORM P — BEACONS AFFECTED');
  y = MARGIN_PT + 30;

  doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
    .text('SCHEDULE OF BEACONS AFFECTED', MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 25;
  // Extinguished beacons
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_WARNING)
    .text(`Extinguished Beacons (${input.extinguishedBeacons.length})`, MARGIN_PT, y);
  y += 16;

  if (input.extinguishedBeacons.length === 0) {
    doc.font('Helvetica-Oblique').fontSize(FS_BODY).fillColor(COLOR_GREY)
      .text('No beacons extinguished in this mutation.', MARGIN_PT, y);
    y += 14;
  } else {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text('Beacon No.', MARGIN_PT, y, { width: 30 * MM_TO_PT })
      .text('Reason for Extinction', MARGIN_PT + 30 * MM_TO_PT, y, { width: 150 * MM_TO_PT });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);
    for (const b of input.extinguishedBeacons) {
      y += 2;
      doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
        .text(b.number, MARGIN_PT, y, { width: 30 * MM_TO_PT });
      doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
        .text(b.reason, MARGIN_PT + 30 * MM_TO_PT, y, { width: 150 * MM_TO_PT });
      y += 12;
      doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
    }
  }

  // New beacons
  y += 12;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_GREEN)
    .text(`New Beacons Placed (${input.newBeacons.length})`, MARGIN_PT, y);
  y += 16;

  const beaconCols = [
    { title: 'Beacon No.', x: MARGIN_PT, w: 25 * MM_TO_PT, align: 'left' as const },
    { title: 'Type', x: MARGIN_PT + 25 * MM_TO_PT, w: 30 * MM_TO_PT, align: 'left' as const },
    { title: 'Easting (m)', x: MARGIN_PT + 55 * MM_TO_PT, w: 35 * MM_TO_PT, align: 'right' as const },
    { title: 'Northing (m)', x: MARGIN_PT + 90 * MM_TO_PT, w: 35 * MM_TO_PT, align: 'right' as const },
    { title: 'Description', x: MARGIN_PT + 125 * MM_TO_PT, w: 60 * MM_TO_PT, align: 'left' as const },
  ];
  for (const c of beaconCols) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(c.title, c.x, y, { width: c.w, align: c.align });
  }
  y += 12;
  doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);

  for (const b of input.newBeacons) {
    y += 2;
    doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(b.number, beaconCols[0].x, y, { width: beaconCols[0].w, align: 'left' });
    doc.font('Helvetica').fontSize(FS_SMALL)
      .text(b.type.replace('_', ' '), beaconCols[1].x, y, { width: beaconCols[1].w, align: 'left' });
    doc.font('Courier').fontSize(FS_SMALL)
      .text(fmtCoord(b.easting), beaconCols[2].x, y, { width: beaconCols[2].w, align: 'right' })
      .text(fmtCoord(b.northing), beaconCols[3].x, y, { width: beaconCols[3].w, align: 'right' });
    doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_GREY)
      .text(b.description ?? '—', beaconCols[4].x, y, { width: beaconCols[4].w, align: 'left' });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
  }

  // Director of Surveys approval block
  y += 20;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('FOR OFFICIAL USE ONLY — DIRECTOR OF SURVEYS', MARGIN_PT, y);
  y += 16;

  const approvalRows: Array<[string, string]> = [
    ['Date Received', '_______________________'],
    ['Examined By', '_______________________'],
    ['Approval Status', '☐ APPROVED    ☐ APPROVED WITH CONDITIONS    ☐ REJECTED'],
    ['Date of Decision', '_______________________'],
    ['Reference Number', '_______________________'],
    ['Conditions (if any)', '_______________________________________________'],
    ['Director of Surveys Signature', '_______________________'],
  ];
  for (const [label, value] of approvalRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  drawFooter(doc, input.project, input.surveyor);

  // End the base PDF
  doc.end();
  await new Promise<void>((resolve, reject) => {
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  // Seal + append certificate page
  const sealResult = await sealAndAppendCertificate(
    input.outputPath,
    input.surveyor,
    input.project,
    (certDoc, _seal) => drawMutationCertificate(certDoc, input),
    input.sealWithRSA,
    input.keypair,
  );

  const stats = fs.statSync(input.outputPath);
  return {
    pdfPath: input.outputPath,
    pdfSizeBytes: stats.size,
    pageCount: 4, // 3 base + 1 cert
    sealed: sealResult.sealed,
    signatureFingerprint: sealResult.fingerprint,
    signedAt: sealResult.signedAt,
    warnings: [...warnings, ...sealResult.warnings],
  };
}

function drawMutationCertificate(doc: PDFKit.PDFDocument, input: FormPInput) {
  const yStart = MARGIN_PT + 30;

  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text("SURVEYOR'S CERTIFICATE — MUTATION", MARGIN_PT, yStart, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Survey Regulations 1994, Regulation 3(2) and Regulation 38',
      MARGIN_PT, yStart + 22, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  let y = yStart + 50;

  const body = [
    `I, ${input.surveyor.name} (Licensed Surveyor No. ${input.surveyor.license}${input.surveyor.firmName ? `, ${input.surveyor.firmName}` : ''}),`,
    `hereby certify that the mutation survey shown on the accompanying plans`,
    `and described in this Form P was executed by me (or under my immediate`,
    `personal supervision) in accordance with the Survey Act (Cap. 299) and`,
    `the Survey Regulations 1994, Regulation 38 (Mutation surveys).`,
    '',
    `Mutation particulars:`,
    `  Parent parcel:   ${input.parentParcel.parcelNumber} (LR ${input.parentParcel.lrNumber})`,
    `  Mutation type:   ${input.project.mutationType.replace('_', ' ')}`,
    `  New parcels:     ${input.newParcels.length} created`,
    `  Total new area:  ${fmtArea(input.newParcels.reduce((s, p) => s + p.areaSqM, 0))} m²`,
    `  Balance area:    ${fmtArea(input.balanceArea?.areaSqM ?? 0)} m² (${input.balanceArea?.purpose ?? '—'})`,
    `  New beacons:     ${input.newBeacons.length} placed`,
    `  Extinguished:    ${input.extinguishedBeacons.length} beacons`,
    '',
    `I further certify that:`,
    `  (a) All new beacons were placed under my personal supervision;`,
    `  (b) The areas of the new parcels have been computed correctly and`,
    `      reconcile with the parent parcel area;`,
    `  (c) The mutation does not affect any road reserve, riparian reserve,`,
    `      or other public utility unless duly authorized;`,
    `  (d) The plans and this form comply with the Survey Regulations 1994.`,
    '',
    `Signature: _______________________________`,
    `          ${input.surveyor.name}`,
    `          Licensed Surveyor No. ${input.surveyor.license}`,
    `Date: ${input.project.surveyDate}`,
  ];

  for (const line of body) {
    if (line.startsWith('Signature:') || line.startsWith('          ') || line.startsWith('Date:')) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(line, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
    } else {
      doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(line, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
    }
    y += 13;
  }

  // The digital seal block is rendered by drawDigitalSealBlock in sealAndAppendCertificate.
}

// (drawSealBlock was here but is now replaced by drawDigitalSealBlock above)

// ══════════════════════════════════════════════════════════════════════
// SURVEYOR'S REPORT (TOPOGRAPHICAL)
// ══════════════════════════════════════════════════════════════════════

export interface TopoReportInput {
  project: CommonProject & {
    clientName: string;
    clientPno?: string;
    purposeOfSurvey: string;        // e.g. 'Proposed residential development'
    approximateArea: number;        // m²
    adjacentParcelNumbers?: string[];
  };
  surveyor: CommonSurveyor;
  methodology: {
    controlEstablishment: string;  // e.g. 'Static GNSS, 2 control stations'
    detailSurvey: string;           // e.g. 'RTK-GNSS + total station pickup'
    equipment: Array<{
      instrument: string;           // e.g. 'Trimble R10 GNSS'
      serialNumber: string;
      calibrationDate: string;
    }>;
    weatherConditions: string;
    fieldCrew: Array<{ name: string; role: string }>;
  };
  controlNetwork: {
    stations: Array<{
      number: string;
      easting: number;
      northing: number;
      elevation: number;
      order: string;                // e.g. '1st order', '2nd order'
      method: string;               // e.g. 'Static GNSS 2hr session'
    }>;
    accuracyAchieved: string;       // e.g. '±5mm + 1ppm horizontal, ±10mm vertical'
  };
  detailPoints: {
    totalPoints: number;
    byCategory: Array<{ category: string; count: number }>;
    breaklines: number;
  };
  deliverables: Array<{
    name: string;                   // e.g. 'Topographic plan'
    format: string;                 // e.g. 'A1 PDF + DXF + Shapefile'
    sheetCount?: number;
  }>;
  accuracy: {
    horizontalRMSE: number;
    verticalRMSE: number;
    contourInterval: number;        // m
    demResolution: number;          // m
  };
  outputPath: string;
  sealWithRSA?: boolean;
  keypair?: SurveyorKeypair;
}

export async function generateTopoSurveyorsReport(input: TopoReportInput): Promise<FormResult> {
  log.info(`Generating Topo Surveyor's Report for ${input.project.parcelNumber}`);

  const warnings: string[] = [];
  if (input.controlNetwork.stations.length < 2) {
    warnings.push('Fewer than 2 control stations — minimum 2 required for topographical survey.');
  }
  if (input.detailPoints.totalPoints === 0) {
    warnings.push('No detail points observed — report will be incomplete.');
  }

  const doc = new PDFDocument({
    size: [A4_WIDTH_PT, A4_HEIGHT_PT],
    margins: { top: MARGIN_PT, bottom: MARGIN_PT, left: MARGIN_PT, right: MARGIN_PT },
    info: {
      Title: `Surveyor's Report (Topographical) — ${input.project.parcelNumber}`,
      Author: `${input.surveyor.name} (Lic. ${input.surveyor.license})`,
      Subject: 'Topographical Survey Report',
      Keywords: 'Survey of Kenya, Topographical, METARDU Desktop',
      Producer: 'METARDU Desktop',
    },
  });

  const stream = fs.createWriteStream(input.outputPath);
  doc.pipe(stream);

  // ─── Page 1: Cover + Project Description ─────────────────────────
  drawHeader(doc, input.project, '1', "SURVEYOR'S REPORT — TOPOGRAPHICAL");

  let y = MARGIN_PT + 30;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text("SURVEYOR'S REPORT", MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
  y += 22;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_BLACK)
    .text('TOPOGRAPHICAL SURVEY', MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
  y += 18;
  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Per Survey of Kenya Practice Notes 2020',
      MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 25;
  const labelW = 50 * MM_TO_PT;
  const valW = (A4_WIDTH_PT - 2 * MARGIN_PT) - labelW;
  const projectRows: Array<[string, string]> = [
    ['Project Name', input.project.name],
    ['Client', input.project.clientName],
    ['Client P/No', input.project.clientPno ?? '—'],
    ['Parcel Number', input.project.parcelNumber],
    ['LR Number', input.project.lrNumber],
    ['County', input.project.county],
    ['Sub-County', input.project.subCounty ?? '—'],
    ['Locality', input.project.locality],
    ['Purpose of Survey', input.project.purposeOfSurvey],
    ['Approximate Area', `${fmtArea(input.project.approximateArea)} m² (${sqMToHa(input.project.approximateArea).toFixed(4)} ha)`],
    ['Adjacent Parcels', input.project.adjacentParcelNumbers?.join(', ') ?? '—'],
    ['Survey Date', input.project.surveyDate],
    ['Projection', input.project.projection],
    ['Datum', input.project.datum],
    ['Surveyor', `${input.surveyor.name} (Lic. ${input.surveyor.license})`],
    ['Surveyor Firm', input.surveyor.firmName ?? '—'],
  ];
  for (const [label, value] of projectRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  drawFooter(doc, input.project, input.surveyor);

  // ─── Page 2: Survey Methodology + Equipment ──────────────────────
  doc.addPage();
  drawHeader(doc, input.project, '2', 'SURVEY METHODOLOGY');
  y = MARGIN_PT + 30;

  doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
    .text('1. SURVEY METHODOLOGY', MARGIN_PT, y);
  y += 20;

  // Narrative
  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text(
      `The topographical survey of ${input.project.locality}, ${input.project.county} County, was conducted on ${input.project.surveyDate}. The survey was undertaken on behalf of ${input.project.clientName} for the purpose of ${input.project.purposeOfSurvey.toLowerCase()}.`,
      MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT, align: 'justify' }
    );
  y += 28;

  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text('1.1 Control Establishment', MARGIN_PT, y);
  y += 14;
  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text(input.methodology.controlEstablishment, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT, align: 'justify' });
  y += 20;

  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text('1.2 Detail Survey', MARGIN_PT, y);
  y += 14;
  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text(input.methodology.detailSurvey, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT, align: 'justify' });
  y += 20;

  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text('1.3 Weather Conditions', MARGIN_PT, y);
  y += 14;
  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text(input.methodology.weatherConditions, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT, align: 'justify' });
  y += 25;

  // Equipment table
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('2. EQUIPMENT USED', MARGIN_PT, y);
  y += 16;

  const eqCols = [
    { title: 'Instrument', x: MARGIN_PT, w: 70 * MM_TO_PT, align: 'left' as const },
    { title: 'Serial No.', x: MARGIN_PT + 70 * MM_TO_PT, w: 40 * MM_TO_PT, align: 'left' as const },
    { title: 'Calibration Date', x: MARGIN_PT + 110 * MM_TO_PT, w: 40 * MM_TO_PT, align: 'left' as const },
  ];
  for (const c of eqCols) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(c.title, c.x, y, { width: c.w, align: c.align });
  }
  y += 12;
  doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);
  for (const eq of input.methodology.equipment) {
    y += 2;
    doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(eq.instrument, eqCols[0].x, y, { width: eqCols[0].w, align: 'left' })
      .text(eq.serialNumber, eqCols[1].x, y, { width: eqCols[1].w, align: 'left' })
      .text(eq.calibrationDate, eqCols[2].x, y, { width: eqCols[2].w, align: 'left' });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
  }

  // Field crew
  y += 12;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('3. FIELD CREW', MARGIN_PT, y);
  y += 16;

  const crewCols = [
    { title: 'Name', x: MARGIN_PT, w: 80 * MM_TO_PT, align: 'left' as const },
    { title: 'Role', x: MARGIN_PT + 80 * MM_TO_PT, w: 70 * MM_TO_PT, align: 'left' as const },
  ];
  for (const c of crewCols) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(c.title, c.x, y, { width: c.w, align: c.align });
  }
  y += 12;
  doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);
  for (const member of input.methodology.fieldCrew) {
    y += 2;
    doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(member.name, crewCols[0].x, y, { width: crewCols[0].w, align: 'left' })
      .text(member.role, crewCols[1].x, y, { width: crewCols[1].w, align: 'left' });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
  }

  drawFooter(doc, input.project, input.surveyor);

  // ─── Page 3: Control Network + Detail Points + Accuracy ─────────
  doc.addPage();
  drawHeader(doc, input.project, '3', 'CONTROL NETWORK + DETAIL POINTS');
  y = MARGIN_PT + 30;

  doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
    .text('4. CONTROL NETWORK', MARGIN_PT, y);
  y += 18;

  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text(`Accuracy achieved: ${input.controlNetwork.accuracyAchieved}`, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
  y += 20;

  // Control stations table
  const ctrlCols = [
    { title: 'Stn No.', x: MARGIN_PT, w: 18 * MM_TO_PT, align: 'left' as const },
    { title: 'Easting (m)', x: MARGIN_PT + 18 * MM_TO_PT, w: 32 * MM_TO_PT, align: 'right' as const },
    { title: 'Northing (m)', x: MARGIN_PT + 50 * MM_TO_PT, w: 32 * MM_TO_PT, align: 'right' as const },
    { title: 'Elev. (m)', x: MARGIN_PT + 82 * MM_TO_PT, w: 22 * MM_TO_PT, align: 'right' as const },
    { title: 'Order', x: MARGIN_PT + 104 * MM_TO_PT, w: 25 * MM_TO_PT, align: 'left' as const },
    { title: 'Method', x: MARGIN_PT + 129 * MM_TO_PT, w: 56 * MM_TO_PT, align: 'left' as const },
  ];
  for (const c of ctrlCols) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(c.title, c.x, y, { width: c.w, align: c.align });
  }
  y += 12;
  doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);
  for (const s of input.controlNetwork.stations) {
    y += 2;
    doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(s.number, ctrlCols[0].x, y, { width: ctrlCols[0].w, align: 'left' });
    doc.font('Courier').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(fmtCoord(s.easting), ctrlCols[1].x, y, { width: ctrlCols[1].w, align: 'right' })
      .text(fmtCoord(s.northing), ctrlCols[2].x, y, { width: ctrlCols[2].w, align: 'right' })
      .text(s.elevation.toFixed(3), ctrlCols[3].x, y, { width: ctrlCols[3].w, align: 'right' });
    doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(s.order, ctrlCols[4].x, y, { width: ctrlCols[4].w, align: 'left' })
      .text(s.method, ctrlCols[5].x, y, { width: ctrlCols[5].w, align: 'left' });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
  }

  // Detail points summary
  y += 16;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
    .text('5. DETAIL POINTS OBSERVED', MARGIN_PT, y);
  y += 18;

  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text(`Total detail points: ${input.detailPoints.totalPoints.toLocaleString()}`, MARGIN_PT, y);
  y += 14;
  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text(`Breaklines observed: ${input.detailPoints.breaklines}`, MARGIN_PT, y);
  y += 20;

  // Category breakdown
  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text('Breakdown by category:', MARGIN_PT, y);
  y += 14;

  for (const cat of input.detailPoints.byCategory) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(`  • ${cat.category}`, MARGIN_PT, y, { width: 100 * MM_TO_PT });
    doc.font('Courier').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(String(cat.count), MARGIN_PT + 100 * MM_TO_PT, y, { width: 30 * MM_TO_PT, align: 'right' });
    y += 13;
  }

  // Accuracy achieved
  y += 12;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
    .text('6. ACCURACY ACHIEVED', MARGIN_PT, y);
  y += 18;

  const accRows: Array<[string, string]> = [
    ['Horizontal RMSE', `±${input.accuracy.horizontalRMSE.toFixed(3)} m`],
    ['Vertical RMSE', `±${input.accuracy.verticalRMSE.toFixed(3)} m`],
    ['Contour Interval', `${input.accuracy.contourInterval.toFixed(1)} m`],
    ['DEM Resolution', `${input.accuracy.demResolution.toFixed(1)} m grid`],
  ];
  for (const [label, value] of accRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Courier').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  drawFooter(doc, input.project, input.surveyor);

  // ─── Page 4: Deliverables + Surveyor's Certificate ───────────────
  doc.addPage();
  drawHeader(doc, input.project, '4', 'DELIVERABLES + CERTIFICATE');
  y = MARGIN_PT + 30;

  doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
    .text('7. DELIVERABLES', MARGIN_PT, y);
  y += 20;

  const delCols = [
    { title: 'Deliverable', x: MARGIN_PT, w: 80 * MM_TO_PT, align: 'left' as const },
    { title: 'Format', x: MARGIN_PT + 80 * MM_TO_PT, w: 80 * MM_TO_PT, align: 'left' as const },
    { title: 'Sheets', x: MARGIN_PT + 160 * MM_TO_PT, w: 25 * MM_TO_PT, align: 'right' as const },
  ];
  for (const c of delCols) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(c.title, c.x, y, { width: c.w, align: c.align });
  }
  y += 12;
  doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);
  for (const d of input.deliverables) {
    y += 2;
    doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(d.name, delCols[0].x, y, { width: delCols[0].w, align: 'left' });
    doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(d.format, delCols[1].x, y, { width: delCols[1].w, align: 'left' })
      .text(d.sheetCount != null ? String(d.sheetCount) : '—', delCols[2].x, y, { width: delCols[2].w, align: 'right' });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
  }

  // Surveyor's certificate (basic — without RSA block, which is appended later)
  y += 20;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
    .text("8. SURVEYOR'S CERTIFICATE", MARGIN_PT, y);
  y += 20;

  const certText = [
    `I, ${input.surveyor.name} (Licensed Surveyor No. ${input.surveyor.license}),`,
    `hereby certify that the topographical survey described in this report`,
    `was executed by me (or under my immediate personal supervision) on`,
    `${input.project.surveyDate}, in accordance with the Survey Act (Cap. 299)`,
    `and the Survey Regulations 1994.`,
    '',
    `I further certify that:`,
    `  (a) All equipment used was calibrated and in good working order;`,
    `  (b) The control network was established to the accuracy stated;`,
    `  (c) All detail points were observed and coded correctly;`,
    `  (d) The deliverables listed above are complete and accurate.`,
    '',
    `Signature: _______________________________`,
    `          ${input.surveyor.name}`,
    `          Licensed Surveyor No. ${input.surveyor.license}`,
    `          ${input.surveyor.firmName ?? ''}`,
    `Date: ${input.project.surveyDate}`,
  ];
  for (const line of certText) {
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(line, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
    y += 13;
  }

  drawFooter(doc, input.project, input.surveyor);

  doc.end();
  await new Promise<void>((resolve, reject) => {
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  const sealResult = await sealAndAppendCertificate(
    input.outputPath,
    input.surveyor,
    input.project,
    (certDoc, _seal) => drawTopoCertPage(certDoc, input),
    input.sealWithRSA,
    input.keypair,
  );

  const stats = fs.statSync(input.outputPath);
  return {
    pdfPath: input.outputPath,
    pdfSizeBytes: stats.size,
    pageCount: 5,
    sealed: sealResult.sealed,
    signatureFingerprint: sealResult.fingerprint,
    signedAt: sealResult.signedAt,
    warnings: [...warnings, ...sealResult.warnings],
  };
}

function drawTopoCertPage(doc: PDFKit.PDFDocument, input: TopoReportInput) {
  const yStart = MARGIN_PT + 30;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text("SURVEYOR'S CERTIFICATE — TOPOGRAPHICAL", MARGIN_PT, yStart, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Survey Regulations 1994, Regulation 3(2)',
      MARGIN_PT, yStart + 22, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  let y = yStart + 50;

  const body = [
    `I, ${input.surveyor.name} (Licensed Surveyor No. ${input.surveyor.license}),`,
    `hereby certify that the topographical survey described in this report`,
    `and shown on the accompanying plans was executed by me (or under my`,
    `immediate personal supervision) on ${input.project.surveyDate}, in`,
    `accordance with the Survey Act (Cap. 299) and the Survey Regulations 1994.`,
    '',
    `Survey particulars:`,
    `  Project:        ${input.project.name}`,
    `  Client:         ${input.project.clientName}`,
    `  Locality:       ${input.project.locality}, ${input.project.county} County`,
    `  Purpose:        ${input.project.purposeOfSurvey}`,
    `  Approx. area:   ${fmtArea(input.project.approximateArea)} m²`,
    `  Control:        ${input.controlNetwork.stations.length} stations, ${input.controlNetwork.accuracyAchieved}`,
    `  Detail points:  ${input.detailPoints.totalPoints.toLocaleString()}`,
    `  Breaklines:     ${input.detailPoints.breaklines}`,
    `  H. RMSE:        ±${input.accuracy.horizontalRMSE.toFixed(3)} m`,
    `  V. RMSE:        ±${input.accuracy.verticalRMSE.toFixed(3)} m`,
    `  Contours:       ${input.accuracy.contourInterval.toFixed(1)} m interval`,
    `  Projection:     ${input.project.projection} on ${input.project.datum}`,
    '',
    `I further certify that the digital seal below is my unique RSA-2048`,
    `signature over the SHA-256 hash of this report.`,
  ];
  for (const line of body) {
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(line, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
    y += 13;
  }
}

// ══════════════════════════════════════════════════════════════════════
// CROSS-SECTION SHEETS (ENGINEERING)
// ══════════════════════════════════════════════════════════════════════

export interface CrossSectionInput {
  project: CommonProject & {
    roadName: string;
    roadClass: string;             // e.g. 'Class B'
    chainageStart: number;         // m
    chainageEnd: number;           // m
    designSpeed: number;           // km/h
    totalLength: number;           // m
  };
  surveyor: CommonSurveyor;
  crossSections: Array<{
    chainage: number;              // m
    existingGround: Array<{ offset: number; elevation: number }>;  // offset from centerline, +ve = right
    designLevel: Array<{ offset: number; elevation: number }>;
    cutArea?: number;              // m² (cut = existing above design)
    fillArea?: number;             // m² (fill = existing below design)
    cutDepth?: number;             // m at centerline (positive = cut, negative = fill)
  }>;
  earthworksSummary: {
    totalCutVolume: number;        // m³
    totalFillVolume: number;       // m³
    netVolume: number;             // m³ (cut - fill, +ve = borrow, -ve = spoil)
    averageCutDepth: number;       // m
    averageFillHeight: number;     // m
    haulDistance: number;          // m (freehaul + overhaul)
  };
  outputPath: string;
  sealWithRSA?: boolean;
  keypair?: SurveyorKeypair;
}

export async function generateCrossSectionSheets(input: CrossSectionInput): Promise<FormResult> {
  log.info(`Generating Cross-Section Sheets for ${input.project.roadName} (${input.crossSections.length} sections)`);

  const warnings: string[] = [];
  if (input.crossSections.length === 0) {
    warnings.push('No cross-sections provided — sheets will be empty.');
  }
  // Validate chainage ordering
  for (let i = 1; i < input.crossSections.length; i++) {
    if (input.crossSections[i].chainage <= input.crossSections[i - 1].chainage) {
      warnings.push(`Chainage not in ascending order at index ${i}.`);
      break;
    }
  }

  const doc = new PDFDocument({
    size: [A4_WIDTH_PT, A4_HEIGHT_PT],
    margins: { top: MARGIN_PT, bottom: MARGIN_PT, left: MARGIN_PT, right: MARGIN_PT },
    info: {
      Title: `Cross-Section Sheets — ${input.project.roadName}`,
      Author: `${input.surveyor.name} (Lic. ${input.surveyor.license})`,
      Subject: `Engineering Cross-Sections (${input.crossSections.length} sections)`,
      Keywords: 'RDM 1.1, Cross-section, Earthworks, METARDU Desktop',
      Producer: 'METARDU Desktop',
    },
  });

  const stream = fs.createWriteStream(input.outputPath);
  doc.pipe(stream);

  // ─── Page 1: Cover + Earthworks Summary ──────────────────────────
  drawHeader(doc, input.project, '1', 'CROSS-SECTION SHEETS — ENGINEERING');

  let y = MARGIN_PT + 30;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text('CROSS-SECTION SHEETS', MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
  y += 22;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_BLACK)
    .text(`${input.project.roadName} (${input.project.roadClass})`, MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
  y += 18;
  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Per Road Design Manual RDM 1.1 (2025), Section 6',
      MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 25;
  const labelW = 50 * MM_TO_PT;
  const valW = (A4_WIDTH_PT - 2 * MARGIN_PT) - labelW;
  const projectRows: Array<[string, string]> = [
    ['Road Name', input.project.roadName],
    ['Road Class', input.project.roadClass],
    ['Design Speed', `${input.project.designSpeed} km/h`],
    ['Chainage Start', `CH ${input.project.chainageStart.toFixed(0).padStart(4, '0')}`],
    ['Chainage End', `CH ${input.project.chainageEnd.toFixed(0).padStart(4, '0')}`],
    ['Total Length', `${fmtDistance(input.project.totalLength)} m`],
    ['Number of Sections', String(input.crossSections.length)],
    ['County', input.project.county],
    ['Locality', input.project.locality],
    ['Survey Date', input.project.surveyDate],
    ['Projection', input.project.projection],
    ['Datum', input.project.datum],
    ['Surveyor', `${input.surveyor.name} (Lic. ${input.surveyor.license})`],
  ];
  for (const [label, value] of projectRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  // Earthworks summary
  y += 12;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('EARTHWORKS SUMMARY', MARGIN_PT, y);
  y += 16;

  const ew = input.earthworksSummary;
  const ewRows: Array<[string, string, string]> = [
    ['Total Cut Volume', `${fmtArea(ew.totalCutVolume)} m³`, 'CUT'],
    ['Total Fill Volume', `${fmtArea(ew.totalFillVolume)} m³`, 'FILL'],
    ['Net Volume', `${(ew.netVolume >= 0 ? '+' : '')}${fmtArea(ew.netVolume)} m³`, ew.netVolume >= 0 ? 'BORROW' : 'SPOIL'],
    ['Average Cut Depth', `${ew.averageCutDepth.toFixed(3)} m`, ''],
    ['Average Fill Height', `${ew.averageFillHeight.toFixed(3)} m`, ''],
    ['Haul Distance', `${fmtDistance(ew.haulDistance)} m`, ''],
  ];
  for (const [label, value, status] of ewRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Courier').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.font('Helvetica-Bold').fontSize(FS_BODY)
      .fillColor(status === 'CUT' ? COLOR_WARNING : status === 'FILL' ? COLOR_BLUE : status === 'BORROW' || status === 'SPOIL' ? COLOR_ACCENT : COLOR_GREY)
      .text(status, MARGIN_PT + labelW + valW, y, { width: 30 * MM_TO_PT });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  drawFooter(doc, input.project, input.surveyor);

  // ─── Pages 2+: Cross-Section Tables ──────────────────────────────
  // Each page holds up to 4 cross-sections (each as a small table block)
  const SECTIONS_PER_PAGE = 4;
  let sectionIdx = 0;
  let pageNum = 2;

  while (sectionIdx < input.crossSections.length) {
    doc.addPage();
    drawHeader(doc, input.project, String(pageNum), 'CROSS-SECTION TABLES');
    let y = MARGIN_PT + 30;

    doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
      .text(`CROSS-SECTION TABLES — SHEET ${pageNum - 1} of ${Math.ceil(input.crossSections.length / SECTIONS_PER_PAGE)}`, MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
    y += 18;

    const sectionsThisPage = Math.min(SECTIONS_PER_PAGE, input.crossSections.length - sectionIdx);

    for (let i = 0; i < sectionsThisPage; i++) {
      const cs = input.crossSections[sectionIdx];
      y = drawCrossSectionBlock(doc, cs, y);

      // Page break if needed before the next section
      if (y > A4_HEIGHT_PT - MARGIN_PT - 60 && i < sectionsThisPage - 1) {
        break;
      }
      sectionIdx++;
    }
    pageNum++;
  }

  drawFooter(doc, input.project, input.surveyor);

  doc.end();
  await new Promise<void>((resolve, reject) => {
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  const sealResult = await sealAndAppendCertificate(
    input.outputPath,
    input.surveyor,
    input.project,
    (certDoc, _seal) => drawCrossSectionCertPage(certDoc, input),
    input.sealWithRSA,
    input.keypair,
  );

  const stats = fs.statSync(input.outputPath);
  return {
    pdfPath: input.outputPath,
    pdfSizeBytes: stats.size,
    pageCount: pageNum + 1,
    sealed: sealResult.sealed,
    signatureFingerprint: sealResult.fingerprint,
    signedAt: sealResult.signedAt,
    warnings: [...warnings, ...sealResult.warnings],
  };
}

function drawCrossSectionBlock(doc: PDFKit.PDFDocument, cs: CrossSectionInput['crossSections'][0], y: number): number {
  // Section header
  doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_ACCENT)
    .text(`CHAINAGE ${cs.chainage.toFixed(0).padStart(4, '0')} m`, MARGIN_PT, y, { width: 60 * MM_TO_PT });
  const cutFillLabel = (cs.cutDepth ?? 0) >= 0
    ? `CUT ${(cs.cutDepth ?? 0).toFixed(3)} m`
    : `FILL ${Math.abs(cs.cutDepth ?? 0).toFixed(3)} m`;
  doc.font('Helvetica-Bold').fontSize(FS_BODY)
    .fillColor((cs.cutDepth ?? 0) >= 0 ? COLOR_WARNING : COLOR_BLUE)
    .text(cutFillLabel, MARGIN_PT + 60 * MM_TO_PT, y, { width: 40 * MM_TO_PT });
  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text(`Cut area: ${(cs.cutArea ?? 0).toFixed(3)} m²`, MARGIN_PT + 100 * MM_TO_PT, y, { width: 40 * MM_TO_PT })
    .text(`Fill area: ${(cs.fillArea ?? 0).toFixed(3)} m²`, MARGIN_PT + 140 * MM_TO_PT, y, { width: 40 * MM_TO_PT });
  y += 14;

  // Existing ground table
  doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
    .text('EXISTING GROUND', MARGIN_PT, y);
  y += 11;

  // Merge existing + design into one table for compactness
  // Use 8 offset points: -15, -10, -5, 0, +5, +10, +15
  const stdOffsets = [-15, -10, -5, 0, 5, 10, 15];

  const cols = [
    { title: 'Offset (m)', x: MARGIN_PT, w: 25 * MM_TO_PT, align: 'right' as const },
    { title: 'Exist. Level', x: MARGIN_PT + 25 * MM_TO_PT, w: 25 * MM_TO_PT, align: 'right' as const },
    { title: 'Design Level', x: MARGIN_PT + 50 * MM_TO_PT, w: 25 * MM_TO_PT, align: 'right' as const },
    { title: 'Cut/Fill (m)', x: MARGIN_PT + 75 * MM_TO_PT, w: 25 * MM_TO_PT, align: 'right' as const },
    { title: 'Status', x: MARGIN_PT + 100 * MM_TO_PT, w: 25 * MM_TO_PT, align: 'left' as const },
  ];
  for (const c of cols) {
    doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(c.title, c.x, y, { width: c.w, align: c.align });
  }
  y += 10;
  doc.moveTo(MARGIN_PT, y).lineTo(MARGIN_PT + 125 * MM_TO_PT, y).lineWidth(0.3).stroke(COLOR_BLACK);

  for (const offset of stdOffsets) {
    const eg = cs.existingGround.find(p => Math.abs(p.offset - offset) < 0.5);
    const dl = cs.designLevel.find(p => Math.abs(p.offset - offset) < 0.5);
    if (!eg && !dl) continue;
    y += 2;
    const existLevel = eg?.elevation;
    const designLvl = dl?.elevation;
    const cutFill = (existLevel != null && designLvl != null) ? designLvl - existLevel : null;
    const status = cutFill == null ? '—' : cutFill > 0 ? 'FILL' : cutFill < 0 ? 'CUT' : '—';

    doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text((offset >= 0 ? '+' : '') + offset.toFixed(1), cols[0].x, y, { width: cols[0].w, align: 'right' });
    doc.font('Courier').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(existLevel != null ? existLevel.toFixed(3) : '—', cols[1].x, y, { width: cols[1].w, align: 'right' })
      .text(designLvl != null ? designLvl.toFixed(3) : '—', cols[2].x, y, { width: cols[2].w, align: 'right' })
      .text(cutFill != null ? cutFill.toFixed(3) : '—', cols[3].x, y, { width: cols[3].w, align: 'right' });
    doc.font('Helvetica-Bold').fontSize(FS_SMALL)
      .fillColor(status === 'CUT' ? COLOR_WARNING : status === 'FILL' ? COLOR_BLUE : COLOR_GREY)
      .text(status, cols[4].x, y, { width: cols[4].w, align: 'left' });
    y += 10;
    doc.moveTo(MARGIN_PT, y).lineTo(MARGIN_PT + 125 * MM_TO_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
  }

  return y + 12;
}

function drawCrossSectionCertPage(doc: PDFKit.PDFDocument, input: CrossSectionInput) {
  const yStart = MARGIN_PT + 30;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text("SURVEYOR'S CERTIFICATE — CROSS-SECTIONS", MARGIN_PT, yStart, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Survey Regulations 1994, Regulation 3(2) — RDM 1.1 Section 6',
      MARGIN_PT, yStart + 22, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  let y = yStart + 50;
  const ew = input.earthworksSummary;
  const body = [
    `I, ${input.surveyor.name} (Licensed Surveyor No. ${input.surveyor.license}),`,
    `hereby certify that the cross-sections shown in these sheets were`,
    `observed and computed by me (or under my immediate personal supervision)`,
    `in accordance with the Survey Act (Cap. 299) and the Road Design`,
    `Manual RDM 1.1 (2025).`,
    '',
    `Engineering particulars:`,
    `  Road:              ${input.project.roadName} (${input.project.roadClass})`,
    `  Design speed:      ${input.project.designSpeed} km/h`,
    `  Chainage range:    CH ${input.project.chainageStart.toFixed(0)} — CH ${input.project.chainageEnd.toFixed(0)}`,
    `  Total length:      ${fmtDistance(input.project.totalLength)} m`,
    `  Sections observed: ${input.crossSections.length}`,
    `  Total cut:         ${fmtArea(ew.totalCutVolume)} m³`,
    `  Total fill:        ${fmtArea(ew.totalFillVolume)} m³`,
    `  Net volume:        ${(ew.netVolume >= 0 ? '+' : '')}${fmtArea(ew.netVolume)} m³ (${ew.netVolume >= 0 ? 'borrow' : 'spoil'})`,
    `  Avg cut depth:     ${ew.averageCutDepth.toFixed(3)} m`,
    `  Avg fill height:   ${ew.averageFillHeight.toFixed(3)} m`,
    `  Haul distance:     ${fmtDistance(ew.haulDistance)} m`,
    '',
    `I further certify that the digital seal below is my unique RSA-2048`,
    `signature over the SHA-256 hash of this report.`,
  ];
  for (const line of body) {
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(line, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
    y += 13;
  }
}
