/**
 * Supplementary Forms — RINEX Observation Log + Leveling Book
 *
 * Two supplementary statutory forms:
 *
 *   1. RINEX OBSERVATION LOG (Topographical)
 *      Per Survey of Kenya GNSS Practice Notes.
 *      Records GNSS observation sessions for post-processing:
 *        - Station info (marker, name, coords)
 *        - Receiver + antenna info
 *        - Session start/stop times (UTC)
 *        - Satellites observed
 *        - Ephemeris source
 *        - Weather conditions
 *        - Operator name
 *
 *   2. LEVELING BOOK (Engineering)
 *      Per Road Design Manual RDM 1.1 (2025), Section 5.
 *      Rise and fall method, page-validated:
 *        - Backsight (BS), foresight (FS) readings
 *        - Rise / fall computation
 *        - Reduced level (RL) computation
 *        - Page check: ∑BS - ∑FS = ∑rise - ∑fall = last RL - first RL
 *        - Closure: 10√K mm (where K = distance in km)
 *
 * All forms sealed with RSA-2048 via shared sealAndAppendCertificate helper.
 */

import PDFDocument from 'pdfkit';
import * as fs from 'node:fs';
import log from 'electron-log/main';
import { sealDocument, loadOrCreateSurveyorKeypair, type SurveyorKeypair } from './crypto-seal.js';

// ─── Constants ─────────────────────────────────────────────────────────
const MM_TO_PT = 2.8346;
const A4_WIDTH_PT = 210 * MM_TO_PT;
const A4_HEIGHT_PT = 297 * MM_TO_PT;
const MARGIN_PT = 15 * MM_TO_PT;

const COLOR_BLACK = '#000000';
const COLOR_GREY = '#666666';
const COLOR_LIGHT_GREY = '#CCCCCC';
const COLOR_ACCENT = '#003366';
const COLOR_WARNING = '#CC0000';
const COLOR_GREEN = '#008800';
const COLOR_BLUE = '#0066CC';

const FS_TITLE = 14;
const FS_HEADING = 11;
const FS_SUBHEADING = 9;
const FS_BODY = 8;
const FS_SMALL = 6.5;

// ─── Shared Types ──────────────────────────────────────────────────────

interface CommonSurveyor {
  name: string;
  license: string;
  firmName?: string;
  postalAddress?: string;
  phoneNumber?: string;
  email?: string;
}

interface CommonProject {
  name: string;
  parcelNumber: string;
  lrNumber: string;
  county: string;
  subCounty?: string;
  locality: string;
  surveyDate: string;
  projection: string;
  datum: string;
  zone?: string;
  directorOfSurveysRef?: string;
}

interface SealInfo {
  signature: string;
  publicKeyPem: string;
  keyFingerprint: string;
  signedAt: string;
  documentHash: string;
}

interface FormResult {
  pdfPath: string;
  pdfSizeBytes: number;
  pageCount: number;
  sealed: boolean;
  signatureFingerprint?: string;
  signedAt?: string;
  warnings: string[];
}

// ─── Shared Helpers ────────────────────────────────────────────────────

function drawHeader(doc: PDFKit.PDFDocument, project: CommonProject, pageNum: string, title: string) {
  const top = MARGIN_PT;
  doc.moveTo(MARGIN_PT, top + 18)
    .lineTo(A4_WIDTH_PT - MARGIN_PT, top + 18)
    .lineWidth(1.2)
    .stroke(COLOR_ACCENT);

  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('REPUBLIC OF KENYA — SURVEY OF KENYA', MARGIN_PT, top);
  doc.font('Helvetica').fontSize(FS_SUBHEADING).fillColor(COLOR_BLACK)
    .text(title, MARGIN_PT, top + 12);
  doc.font('Helvetica').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text(`Page ${pageNum}`, A4_WIDTH_PT - 80, top, { width: 65, align: 'right' });
}

function drawFooter(doc: PDFKit.PDFDocument, project: CommonProject, surveyor: CommonSurveyor) {
  const bottom = A4_HEIGHT_PT - MARGIN_PT - 14;
  doc.moveTo(MARGIN_PT, bottom)
    .lineTo(A4_WIDTH_PT - MARGIN_PT, bottom)
    .lineWidth(0.5)
    .stroke(COLOR_GREY);
  doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_GREY)
    .text(
      `Surveyor: ${surveyor.name} (Lic. ${surveyor.license})  •  Parcel: ${project.parcelNumber}  •  LR: ${project.lrNumber}  •  Generated by METARDU Desktop`,
      MARGIN_PT, bottom + 3,
      { width: A4_WIDTH_PT - 2 * MARGIN_PT, align: 'center' }
    );
}

function fmtCoord(v: number): string { return v.toFixed(3); }
function fmtDistance(v: number): string { return v.toFixed(3); }
function fmtArea(v: number): string {
  return v.toLocaleString('en-KE', { minimumFractionDigits: 3, maximumFractionDigits: 3 });
}

async function sealAndAppendCertificate(
  basePath: string,
  surveyor: CommonSurveyor,
  project: CommonProject,
  drawCertPage: (doc: PDFKit.PDFDocument, seal: SealInfo) => void,
  sealWithRSA: boolean,
  keypair?: SurveyorKeypair,
): Promise<{ sealed: boolean; fingerprint?: string; signedAt?: string; warnings: string[] }> {
  const warnings: string[] = [];
  const pdfBytes = fs.readFileSync(basePath);
  const crypto = await import('node:crypto');
  const documentHash = crypto.createHash('sha256').update(pdfBytes).digest('hex');

  let sealed = false;
  let fingerprint: string | undefined;
  let signedAt: string | undefined;

  if (sealWithRSA !== false) {
    try {
      const kp = keypair ?? loadOrCreateSurveyorKeypair();
      const seal = sealDocument(documentHash, kp);
      sealed = true;
      fingerprint = seal.keyFingerprint;
      signedAt = seal.signedAt;

      const sealInfo: SealInfo = {
        signature: seal.signature,
        publicKeyPem: seal.publicKeyPem,
        keyFingerprint: seal.keyFingerprint,
        signedAt: seal.signedAt,
        documentHash,
      };

      const certDoc = new PDFDocument({
        size: [A4_WIDTH_PT, A4_HEIGHT_PT],
        margins: { top: MARGIN_PT, bottom: MARGIN_PT, left: MARGIN_PT, right: MARGIN_PT },
      });
      const tmpPath = basePath + '.cert.tmp';
      const stream = fs.createWriteStream(tmpPath);
      certDoc.pipe(stream);

      drawHeader(certDoc, project, 'Cert', "Surveyor's Certificate");
      drawCertPage(certDoc, sealInfo);
      drawDigitalSealBlock(certDoc, sealInfo);
      drawFooter(certDoc, project, surveyor);
      certDoc.end();

      await new Promise<void>((resolve, reject) => {
        stream.on('finish', () => resolve());
        stream.on('error', reject);
      });

      const pdfLib = await import('pdf-lib');
      const basePdf = await pdfLib.PDFDocument.load(fs.readFileSync(basePath));
      const certPdf = await pdfLib.PDFDocument.load(fs.readFileSync(tmpPath));
      const copiedPages = await basePdf.copyPages(certPdf, certPdf.getPageIndices());
      for (const p of copiedPages) basePdf.addPage(p);
      const mergedBytes = await basePdf.save();
      fs.writeFileSync(basePath, mergedBytes);
      fs.unlinkSync(tmpPath);
    } catch (err) {
      log.error('RSA sealing failed: ' + String(err));
      warnings.push(`RSA sealing failed: ${String(err)}`);
    }
  }

  return { sealed, fingerprint, signedAt, warnings };
}

function drawDigitalSealBlock(doc: PDFKit.PDFDocument, seal: SealInfo) {
  let y = A4_HEIGHT_PT - MARGIN_PT - 110;

  doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_ACCENT);
  y += 8;

  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
    .text('Digital Seal (RSA-2048)', MARGIN_PT, y);
  y += 16;

  doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
    .text('This document is digitally sealed with RSA-SHA256. Verification:', MARGIN_PT, y);
  y += 14;

  const labelW = 50 * MM_TO_PT;
  const sealRows: Array<[string, string]> = [
    ['Algorithm', 'RSA-SHA256 (RSA-2048 keypair)'],
    ['Signed at', seal.signedAt],
    ['Document hash (SHA-256)', seal.documentHash],
    ['Key fingerprint', seal.keyFingerprint],
    ['Public key', seal.publicKeyPem.split('\n').slice(0, 2).join(' ') + ' …'],
    ['Signature (base64)', seal.signature.substring(0, 64) + ' …'],
  ];
  for (const [label, value] of sealRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Courier').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: A4_WIDTH_PT - MARGIN_PT - labelW });
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
  }
}

// ══════════════════════════════════════════════════════════════════════
// RINEX OBSERVATION LOG
// ══════════════════════════════════════════════════════════════════════

export interface RinexSession {
  stationName: string;
  stationMarker: string;          // e.g. "TS1 - Concrete pillar"
  approxEasting: number;
  approxNorthing: number;
  approxElevation: number;        // m
  receiverMake: string;
  receiverModel: string;
  receiverSerial: string;
  receiverFirmware: string;
  antennaMake: string;
  antennaModel: string;
  antennaSerial: string;
  antennaHeight: number;          // m (vertical)
  heightMeasurementMethod: string; // e.g. "Slant to notch, corrected to vertical"
  sessionStartUTC: string;        // ISO datetime
  sessionEndUTC: string;
  sessionDuration: number;        // seconds
  observationInterval: number;    // seconds (e.g. 15, 30)
  satellitesObserved: string[];   // e.g. ["G01", "G07", "G15", ...]
  ephemerisSource: string;        // e.g. "Broadcast + precise"
  weather: {
    temperature: number;          // °C
    pressure: number;             // hPa
    humidity: number;             // %
    conditions: string;           // e.g. "Partly cloudy"
  };
  operatorName: string;
  notes?: string;
}

export interface RinexLogInput {
  project: CommonProject & {
    corsStations?: Array<{ name: string; distance: number; azimuth: string }>;
    processingCenter?: string;
  };
  surveyor: CommonSurveyor;
  sessions: RinexSession[];
  outputPath: string;
  sealWithRSA?: boolean;
  keypair?: SurveyorKeypair;
}

export async function generateRinexLog(input: RinexLogInput): Promise<FormResult> {
  log.info(`Generating RINEX Observation Log (${input.sessions.length} sessions)`);

  const warnings: string[] = [];
  if (input.sessions.length === 0) {
    warnings.push('No observation sessions provided.');
  }
  for (let i = 0; i < input.sessions.length; i++) {
    const s = input.sessions[i];
    if (s.sessionDuration < 1800) {
      warnings.push(`Session ${i + 1} (${s.stationName}): duration ${s.sessionDuration}s < 30min minimum for static GNSS.`);
    }
    if (s.satellitesObserved.length < 4) {
      warnings.push(`Session ${i + 1} (${s.stationName}): only ${s.satellitesObserved.length} satellites observed (<4 minimum).`);
    }
    if (s.antennaHeight <= 0) {
      warnings.push(`Session ${i + 1} (${s.stationName}): antenna height ${s.antennaHeight}m is invalid.`);
    }
  }

  const doc = new PDFDocument({
    size: [A4_WIDTH_PT, A4_HEIGHT_PT],
    margins: { top: MARGIN_PT, bottom: MARGIN_PT, left: MARGIN_PT, right: MARGIN_PT },
    info: {
      Title: `RINEX Observation Log — ${input.project.parcelNumber}`,
      Author: `${input.surveyor.name} (Lic. ${input.surveyor.license})`,
      Subject: 'GNSS Observation Sessions',
      Keywords: 'GNSS, RINEX, METARDU Desktop',
      Producer: 'METARDU Desktop',
    },
  });

  const stream = fs.createWriteStream(input.outputPath);
  doc.pipe(stream);

  // ─── Page 1: Header + Project Info + CORS Stations ────────────────
  drawHeader(doc, input.project, '1', 'RINEX OBSERVATION LOG');

  let y = MARGIN_PT + 30;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text('RINEX OBSERVATION LOG', MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
  y += 22;
  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Per Survey of Kenya GNSS Practice Notes 2020',
      MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 22;
  const labelW = 50 * MM_TO_PT;
  const valW = (A4_WIDTH_PT - 2 * MARGIN_PT) - labelW;
  const projectRows: Array<[string, string]> = [
    ['Project Name', input.project.name],
    ['Parcel Number', input.project.parcelNumber],
    ['LR Number', input.project.lrNumber],
    ['County', input.project.county],
    ['Sub-County', input.project.subCounty ?? '—'],
    ['Locality', input.project.locality],
    ['Survey Date', input.project.surveyDate],
    ['Projection', input.project.projection],
    ['Datum', input.project.datum],
    ['Surveyor', `${input.surveyor.name} (Lic. ${input.surveyor.license})`],
    ['Surveyor Firm', input.surveyor.firmName ?? '—'],
    ['Processing Center', input.project.processingCenter ?? '—'],
    ['Total Sessions', String(input.sessions.length)],
  ];
  for (const [label, value] of projectRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  // CORS stations
  if (input.project.corsStations && input.project.corsStations.length > 0) {
    y += 10;
    doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
      .text('CORS Reference Stations', MARGIN_PT, y);
    y += 16;
    const cols = [
      { title: 'Station Name', x: MARGIN_PT, w: 60 * MM_TO_PT, align: 'left' as const },
      { title: 'Distance (km)', x: MARGIN_PT + 60 * MM_TO_PT, w: 40 * MM_TO_PT, align: 'right' as const },
      { title: 'Azimuth', x: MARGIN_PT + 100 * MM_TO_PT, w: 40 * MM_TO_PT, align: 'left' as const },
    ];
    for (const c of cols) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(c.title, c.x, y, { width: c.w, align: c.align });
    }
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);
    for (const cors of input.project.corsStations) {
      y += 2;
      doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
        .text(cors.name, cols[0].x, y, { width: cols[0].w, align: 'left' });
      doc.font('Courier').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
        .text(cors.distance.toFixed(1), cols[1].x, y, { width: cols[1].w, align: 'right' });
      doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
        .text(cors.azimuth, cols[2].x, y, { width: cols[2].w, align: 'left' });
      y += 12;
      doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);
    }
  }

  drawFooter(doc, input.project, input.surveyor);

  // ─── Pages 2+: One page per session ──────────────────────────────
  for (let i = 0; i < input.sessions.length; i++) {
    const s = input.sessions[i];
    doc.addPage();
    drawHeader(doc, input.project, String(i + 2), `SESSION ${i + 1} — ${s.stationName}`);
    y = MARGIN_PT + 30;

    doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
      .text(`SESSION ${i + 1} — ${s.stationName}`, MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
    y += 22;

    // Station info
    doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
      .text('Station Information', MARGIN_PT, y);
    y += 16;

    const stationRows: Array<[string, string]> = [
      ['Station Name', s.stationName],
      ['Marker Type', s.stationMarker],
      ['Approx. Easting', fmtCoord(s.approxEasting) + ' m'],
      ['Approx. Northing', fmtCoord(s.approxEasting) + ' m'],
      ['Approx. Elevation', s.approxElevation.toFixed(3) + ' m'],
    ];
    for (const [label, value] of stationRows) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(label, MARGIN_PT, y, { width: labelW });
      doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(value, MARGIN_PT + labelW, y, { width: valW });
      doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
      y += 14;
    }

    // Receiver info
    y += 8;
    doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
      .text('Receiver Information', MARGIN_PT, y);
    y += 16;

    const receiverRows: Array<[string, string]> = [
      ['Make', s.receiverMake],
      ['Model', s.receiverModel],
      ['Serial Number', s.receiverSerial],
      ['Firmware', s.receiverFirmware],
    ];
    for (const [label, value] of receiverRows) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(label, MARGIN_PT, y, { width: labelW });
      doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(value, MARGIN_PT + labelW, y, { width: valW });
      doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
      y += 14;
    }

    // Antenna info
    y += 8;
    doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
      .text('Antenna Information', MARGIN_PT, y);
    y += 16;

    const antennaRows: Array<[string, string]> = [
      ['Make', s.antennaMake],
      ['Model', s.antennaModel],
      ['Serial Number', s.antennaSerial],
      ['Antenna Height', s.antennaHeight.toFixed(3) + ' m'],
      ['Measurement Method', s.heightMeasurementMethod],
    ];
    for (const [label, value] of antennaRows) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(label, MARGIN_PT, y, { width: labelW });
      doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(value, MARGIN_PT + labelW, y, { width: valW });
      doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
      y += 14;
    }

    // Session info
    y += 8;
    doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
      .text('Session Information', MARGIN_PT, y);
    y += 16;

    const sessionRows: Array<[string, string]> = [
      ['Session Start (UTC)', s.sessionStartUTC],
      ['Session End (UTC)', s.sessionEndUTC],
      ['Duration', `${Math.floor(s.sessionDuration / 60)} min ${s.sessionDuration % 60} sec`],
      ['Observation Interval', `${s.observationInterval} s`],
      ['Satellites Observed', `${s.satellitesObserved.length} (${s.satellitesObserved.join(', ')})`],
      ['Ephemeris Source', s.ephemerisSource],
      ['Operator', s.operatorName],
    ];
    for (const [label, value] of sessionRows) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(label, MARGIN_PT, y, { width: labelW });
      doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(value, MARGIN_PT + labelW, y, { width: valW });
      doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
      y += 14;
    }

    // Weather
    y += 8;
    doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
      .text('Weather Conditions', MARGIN_PT, y);
    y += 16;

    const weatherRows: Array<[string, string]> = [
      ['Temperature', `${s.weather.temperature.toFixed(1)} °C`],
      ['Pressure', `${s.weather.pressure.toFixed(1)} hPa`],
      ['Humidity', `${s.weather.humidity.toFixed(0)} %`],
      ['Conditions', s.weather.conditions],
    ];
    for (const [label, value] of weatherRows) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(label, MARGIN_PT, y, { width: labelW });
      doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(value, MARGIN_PT + labelW, y, { width: valW });
      doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
      y += 14;
    }

    // Notes
    if (s.notes) {
      y += 8;
      doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
        .text('Notes', MARGIN_PT, y);
      y += 14;
      doc.font('Helvetica-Oblique').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(s.notes, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
    }

    drawFooter(doc, input.project, input.surveyor);
  }

  doc.end();
  await new Promise<void>((resolve, reject) => {
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  const sealResult = await sealAndAppendCertificate(
    input.outputPath,
    input.surveyor,
    input.project,
    (certDoc, _seal) => drawRinexCertPage(certDoc, input),
    input.sealWithRSA,
    input.keypair,
  );

  const stats = fs.statSync(input.outputPath);
  return {
    pdfPath: input.outputPath,
    pdfSizeBytes: stats.size,
    pageCount: 1 + input.sessions.length + 1, // header + sessions + cert
    sealed: sealResult.sealed,
    signatureFingerprint: sealResult.fingerprint,
    signedAt: sealResult.signedAt,
    warnings: [...warnings, ...sealResult.warnings],
  };
}

function drawRinexCertPage(doc: PDFKit.PDFDocument, input: RinexLogInput) {
  const yStart = MARGIN_PT + 30;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text("SURVEYOR'S CERTIFICATE — GNSS OBSERVATIONS", MARGIN_PT, yStart, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Survey Regulations 1994, Regulation 3(2)',
      MARGIN_PT, yStart + 22, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  let y = yStart + 50;
  const totalDuration = input.sessions.reduce((s, sess) => s + sess.sessionDuration, 0);
  const body = [
    `I, ${input.surveyor.name} (Licensed Surveyor No. ${input.surveyor.license}),`,
    `hereby certify that the GNSS observations described in this log were`,
    `conducted by me (or under my immediate personal supervision) on`,
    `${input.project.surveyDate}, in accordance with the Survey Act (Cap. 299)`,
    `and the Survey Regulations 1994.`,
    '',
    `Observation particulars:`,
    `  Project:           ${input.project.name}`,
    `  Locality:          ${input.project.locality}, ${input.project.county} County`,
    `  Total sessions:    ${input.sessions.length}`,
    `  Total duration:    ${Math.floor(totalDuration / 3600)}h ${Math.floor((totalDuration % 3600) / 60)}m`,
    `  Stations observed: ${input.sessions.map(s => s.stationName).join(', ')}`,
    `  Processing center: ${input.project.processingCenter ?? '—'}`,
    '',
    `I further certify that:`,
    `  (a) All equipment was calibrated and functioning correctly;`,
    `  (b) Antenna heights were measured and recorded before and after each session;`,
    `  (c) The observation log is complete and accurate to the best of my knowledge.`,
  ];
  for (const line of body) {
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(line, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
    y += 13;
  }
}

// ══════════════════════════════════════════════════════════════════════
// LEVELING BOOK (Rise and Fall Method)
// ══════════════════════════════════════════════════════════════════════

export interface LevelingReading {
  station: string;              // staff station label
  backsight?: number;           // staff reading (m), if a BS was taken
  foresight?: number;           // staff reading (m), if a FS was taken
  intermediateSight?: number;   // staff reading (m), if IS
  changePoint?: boolean;        // mark as change point
  distance?: number;            // m, distance to staff (for closure calc)
  remarks?: string;
}

export interface LevelingPage {
  pageNumber: number;
  benchmarkStart: { name: string; elevation: number };  // m
  benchmarkEnd?: { name: string; elevation: number };     // m (for closing run)
  readings: LevelingReading[];
  // Computed:
  pageCheck?: {
    sumBS: number;
    sumFS: number;
    sumRise: number;
    sumFall: number;
    firstRL: number;
    lastRL: number;
    bsMinusFs: number;
    riseMinusFall: number;
    lastMinusFirst: number;
    pageCheckPass: boolean;
  };
}

export interface LevelingBookInput {
  project: CommonProject & {
    roadName?: string;
    roadClass?: string;
    levelType: string;          // e.g. "Automatic Level (Leica NA2)", "Digital Level (Trimble DiNi)"
    levelSerial: string;
    staffType: string;           // e.g. "Fiberglass 5m", "Barcoded 3m"
    staffSerial: string;
    closureStandard: string;    // e.g. "10*sqrt(K) mm (RDM 1.1)"
  };
  surveyor: CommonSurveyor;
  pages: LevelingPage[];
  // Closure results:
  closure?: {
    totalDistance: number;       // m
    numberOfSetups: number;
    misclosure: number;          // mm
    allowable: number;           // mm
    passes: boolean;
    precisionClass: string;      // e.g. "Class I (Engineering) — 1st order"
  };
  outputPath: string;
  sealWithRSA?: boolean;
  keypair?: SurveyorKeypair;
}

export async function generateLevelingBook(input: LevelingBookInput): Promise<FormResult> {
  log.info(`Generating Leveling Book (${input.pages.length} pages)`);

  const warnings: string[] = [];
  if (input.pages.length === 0) {
    warnings.push('No leveling pages provided.');
  }
  // Compute page checks if not provided
  for (let i = 0; i < input.pages.length; i++) {
    const p = input.pages[i];
    let sumBS = 0, sumFS = 0, sumRise = 0, sumFall = 0;
    let prevReading: number | null = null;
    let firstRL = p.benchmarkStart.elevation;
    let currentRL = firstRL;
    let lastRL = firstRL;

    for (const r of p.readings) {
      if (r.backsight != null) {
        sumBS += r.backsight;
        if (prevReading != null) {
          // rise/fall from previous FS to this BS
          const diff = prevReading - r.backsight;
          if (diff >= 0) sumRise += diff; else sumFall += Math.abs(diff);
          currentRL += diff;
        }
      }
      if (r.foresight != null) {
        sumFS += r.foresight;
        if (prevReading != null) {
          // rise/fall from previous BS to this FS
          const diff = prevReading - r.foresight;
          if (diff >= 0) sumRise += diff; else sumFall += Math.abs(diff);
          currentRL += diff;
        }
        prevReading = r.foresight;
        lastRL = currentRL;
      } else if (r.backsight != null) {
        prevReading = r.backsight;
      }
    }

    const bsMinusFs = sumBS - sumFS;
    const riseMinusFall = sumRise - sumFall;
    const lastMinusFirst = lastRL - firstRL;
    const pageCheckPass = Math.abs(bsMinusFs - riseMinusFall) < 0.001 && Math.abs(riseMinusFall - lastMinusFirst) < 0.001;

    if (!p.pageCheck) {
      p.pageCheck = { sumBS, sumFS, sumRise, sumFall, firstRL, lastRL, bsMinusFs, riseMinusFall, lastMinusFirst, pageCheckPass };
    }
    if (!pageCheckPass) {
      warnings.push(`Page ${p.pageNumber}: page check failed (BS-FS=${bsMinusFs.toFixed(3)}, rise-fall=${riseMinusFall.toFixed(3)}, last-first=${lastMinusFirst.toFixed(3)}).`);
    }
  }

  // Closure check
  if (input.closure) {
    const c = input.closure;
    if (!c.passes) {
      warnings.push(`Run closure failed: ${c.misclosure.toFixed(1)}mm > ${c.allowable.toFixed(1)}mm allowable.`);
    }
  }

  const doc = new PDFDocument({
    size: [A4_WIDTH_PT, A4_HEIGHT_PT],
    margins: { top: MARGIN_PT, bottom: MARGIN_PT, left: MARGIN_PT, right: MARGIN_PT },
    info: {
      Title: `Leveling Book — ${input.project.parcelNumber}`,
      Author: `${input.surveyor.name} (Lic. ${input.surveyor.license})`,
      Subject: 'Leveling Book (Rise and Fall Method)',
      Keywords: 'RDM 1.1, Leveling, METARDU Desktop',
      Producer: 'METARDU Desktop',
    },
  });

  const stream = fs.createWriteStream(input.outputPath);
  doc.pipe(stream);

  // ─── Page 1: Cover + Equipment + Closure Summary ─────────────────
  drawHeader(doc, input.project, '1', 'LEVELING BOOK — RISE AND FALL METHOD');

  let y = MARGIN_PT + 30;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text('LEVELING BOOK', MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
  y += 22;
  doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_BLACK)
    .text('RISE AND FALL METHOD', MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
  y += 18;
  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Per Road Design Manual RDM 1.1 (2025), Section 5',
      MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  y += 22;
  const labelW = 50 * MM_TO_PT;
  const valW = (A4_WIDTH_PT - 2 * MARGIN_PT) - labelW;
  const projectRows: Array<[string, string]> = [
    ['Project Name', input.project.name],
    ['Parcel Number', input.project.parcelNumber],
    ['LR Number', input.project.lrNumber],
    ['County', input.project.county],
    ['Locality', input.project.locality],
    ['Road Name', input.project.roadName ?? '—'],
    ['Road Class', input.project.roadClass ?? '—'],
    ['Survey Date', input.project.surveyDate],
    ['Surveyor', `${input.surveyor.name} (Lic. ${input.surveyor.license})`],
    ['Surveyor Firm', input.surveyor.firmName ?? '—'],
    ['Level Type', input.project.levelType],
    ['Level Serial', input.project.levelSerial],
    ['Staff Type', input.project.staffType],
    ['Staff Serial', input.project.staffSerial],
    ['Closure Standard', input.project.closureStandard],
    ['Total Pages', String(input.pages.length)],
  ];
  for (const [label, value] of projectRows) {
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(label, MARGIN_PT, y, { width: labelW });
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(value, MARGIN_PT + labelW, y, { width: valW });
    doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
    y += 14;
  }

  // Closure summary
  if (input.closure) {
    y += 12;
    doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
      .text('RUN CLOSURE SUMMARY', MARGIN_PT, y);
    y += 16;

    const c = input.closure;
    const closureRows: Array<[string, string, string]> = [
      ['Total Distance', `${fmtDistance(c.totalDistance)} m`, ''],
      ['Number of Setups', String(c.numberOfSetups), ''],
      ['Misclosure', `${c.misclosure.toFixed(2)} mm`, ''],
      ['Allowable', `${c.allowable.toFixed(2)} mm`, c.closureStandard],
      ['Result', c.passes ? 'PASS' : 'FAIL', c.passes ? 'OK' : 'CHECK'],
      ['Precision Class', c.precisionClass, ''],
    ];
    for (const [label, value, status] of closureRows) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(label, MARGIN_PT, y, { width: labelW });
      doc.font('Courier').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(value, MARGIN_PT + labelW, y, { width: valW });
      doc.font('Helvetica-Bold').fontSize(FS_BODY)
        .fillColor(status === 'OK' || status === 'PASS' ? COLOR_BLACK : status === 'CHECK' || status === 'FAIL' ? COLOR_WARNING : COLOR_GREY)
        .text(status, MARGIN_PT + labelW + valW, y, { width: 30 * MM_TO_PT });
      doc.moveTo(MARGIN_PT, y + 12).lineTo(A4_WIDTH_PT - MARGIN_PT, y + 12).lineWidth(0.2).stroke(COLOR_LIGHT_GREY);
      y += 14;
    }
  }

  drawFooter(doc, input.project, input.surveyor);

  // ─── Pages 2+: One per leveling page ─────────────────────────────
  for (let i = 0; i < input.pages.length; i++) {
    const p = input.pages[i];
    doc.addPage();
    drawHeader(doc, input.project, String(i + 2), `LEVELING PAGE ${p.pageNumber}`);
    y = MARGIN_PT + 30;

    doc.font('Helvetica-Bold').fontSize(FS_TITLE).fillColor(COLOR_ACCENT)
      .text(`PAGE ${p.pageNumber}`, MARGIN_PT, y, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });
    y += 18;

    // Bench mark info
    doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(`Starting BM: ${p.benchmarkStart.name} (RL ${p.benchmarkStart.elevation.toFixed(3)} m)`, MARGIN_PT, y, { width: 80 * MM_TO_PT });
    if (p.benchmarkEnd) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(`Closing BM: ${p.benchmarkEnd.name} (RL ${p.benchmarkEnd.elevation.toFixed(3)} m)`, MARGIN_PT + 80 * MM_TO_PT, y, { width: 80 * MM_TO_PT });
    }
    y += 16;

    // Readings table header
    const cols = [
      { title: 'Stn', x: MARGIN_PT, w: 18 * MM_TO_PT, align: 'left' as const },
      { title: 'BS (m)', x: MARGIN_PT + 18 * MM_TO_PT, w: 18 * MM_TO_PT, align: 'right' as const },
      { title: 'IS (m)', x: MARGIN_PT + 36 * MM_TO_PT, w: 18 * MM_TO_PT, align: 'right' as const },
      { title: 'FS (m)', x: MARGIN_PT + 54 * MM_TO_PT, w: 18 * MM_TO_PT, align: 'right' as const },
      { title: 'Rise', x: MARGIN_PT + 72 * MM_TO_PT, w: 18 * MM_TO_PT, align: 'right' as const },
      { title: 'Fall', x: MARGIN_PT + 90 * MM_TO_PT, w: 18 * MM_TO_PT, align: 'right' as const },
      { title: 'RL (m)', x: MARGIN_PT + 108 * MM_TO_PT, w: 24 * MM_TO_PT, align: 'right' as const },
      { title: 'Dist (m)', x: MARGIN_PT + 132 * MM_TO_PT, w: 22 * MM_TO_PT, align: 'right' as const },
      { title: 'Remarks', x: MARGIN_PT + 154 * MM_TO_PT, w: 41 * MM_TO_PT, align: 'left' as const },
    ];
    for (const c of cols) {
      doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
        .text(c.title, c.x, y, { width: c.w, align: c.align });
    }
    y += 12;
    doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);

    // Readings rows (with rise/fall computation)
    let prevReading: number | null = null;
    let currentRL = p.benchmarkStart.elevation;

    for (const r of p.readings) {
      y += 2;
      let rise = 0, fall = 0;
      const reading = r.foresight ?? r.backsight ?? r.intermediateSight ?? 0;

      if (r.foresight != null && prevReading != null) {
        const diff = prevReading - r.foresight;
        if (diff >= 0) rise = diff; else fall = Math.abs(diff);
        currentRL += diff;
      } else if (r.backsight != null && prevReading != null) {
        const diff = prevReading - r.backsight;
        if (diff >= 0) rise = diff; else fall = Math.abs(diff);
        currentRL += diff;
      }

      // Row
      doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
        .text(r.station, cols[0].x, y, { width: cols[0].w, align: 'left' });
      doc.font('Courier').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
        .text(r.backsight != null ? r.backsight.toFixed(3) : '', cols[1].x, y, { width: cols[1].w, align: 'right' })
        .text(r.intermediateSight != null ? r.intermediateSight.toFixed(3) : '', cols[2].x, y, { width: cols[2].w, align: 'right' })
        .text(r.foresight != null ? r.foresight.toFixed(3) : '', cols[3].x, y, { width: cols[3].w, align: 'right' })
        .text(rise > 0 ? rise.toFixed(3) : '', cols[4].x, y, { width: cols[4].w, align: 'right' })
        .text(fall > 0 ? fall.toFixed(3) : '', cols[5].x, y, { width: cols[5].w, align: 'right' })
        .text(currentRL.toFixed(3), cols[6].x, y, { width: cols[6].w, align: 'right' })
        .text(r.distance != null ? r.distance.toFixed(1) : '', cols[7].x, y, { width: cols[7].w, align: 'right' });
      doc.font('Helvetica').fontSize(FS_SMALL).fillColor(COLOR_GREY)
        .text(r.remarks ?? '', cols[8].x, y, { width: cols[8].w, align: 'left' });
      y += 11;
      doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.1).stroke(COLOR_LIGHT_GREY);

      // Update prevReading for next iteration
      if (r.foresight != null) prevReading = r.foresight;
      else if (r.backsight != null) prevReading = r.backsight;

      // Page break if needed
      if (y > A4_HEIGHT_PT - MARGIN_PT - 50) {
        // Add continuation page
        doc.addPage();
        drawHeader(doc, input.project, `${i + 2} (cont.)`, `LEVELING PAGE ${p.pageNumber} (cont.)`);
        y = MARGIN_PT + 30;
        for (const c of cols) {
          doc.font('Helvetica-Bold').fontSize(FS_BODY).fillColor(COLOR_BLACK)
            .text(c.title, c.x, y, { width: c.w, align: c.align });
        }
        y += 12;
        doc.moveTo(MARGIN_PT, y).lineTo(A4_WIDTH_PT - MARGIN_PT, y).lineWidth(0.5).stroke(COLOR_BLACK);
      }
    }

    // Page check
    if (p.pageCheck) {
      const pc = p.pageCheck;
      y += 8;
      doc.font('Helvetica-Bold').fontSize(FS_HEADING).fillColor(COLOR_ACCENT)
        .text('PAGE CHECK', MARGIN_PT, y);
      y += 14;

      const checkRows: Array<[string, string, string, string]> = [
        ['Sum BS', pc.sumBS.toFixed(3), 'Sum FS', pc.sumFS.toFixed(3)],
        ['Sum Rise', pc.sumRise.toFixed(3), 'Sum Fall', pc.sumFall.toFixed(3)],
        ['BS - FS', pc.bsMinusFs.toFixed(3), 'Rise - Fall', pc.riseMinusFall.toFixed(3)],
        ['First RL', pc.firstRL.toFixed(3), 'Last RL', pc.lastRL.toFixed(3)],
        ['Last - First', pc.lastMinusFirst.toFixed(3), 'Page Check', pc.pageCheckPass ? 'PASS' : 'FAIL'],
      ];
      const colW = 35 * MM_TO_PT;
      for (const [l1, v1, l2, v2] of checkRows) {
        doc.font('Helvetica-Bold').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
          .text(l1, MARGIN_PT, y, { width: colW })
          .text(l2, MARGIN_PT + 2 * colW, y, { width: colW });
        doc.font('Courier').fontSize(FS_SMALL).fillColor(COLOR_BLACK)
          .text(v1, MARGIN_PT + colW, y, { width: colW, align: 'right' });
        doc.font('Courier').fontSize(FS_SMALL)
          .fillColor(l2 === 'Page Check' && !pc.pageCheckPass ? COLOR_WARNING : COLOR_BLACK)
          .text(v2, MARGIN_PT + 3 * colW, y, { width: colW, align: 'right' });
        y += 11;
      }
    }

    drawFooter(doc, input.project, input.surveyor);
  }

  doc.end();
  await new Promise<void>((resolve, reject) => {
    stream.on('finish', () => resolve());
    stream.on('error', reject);
  });

  const sealResult = await sealAndAppendCertificate(
    input.outputPath,
    input.surveyor,
    input.project,
    (certDoc, _seal) => drawLevelingCertPage(certDoc, input),
    input.sealWithRSA,
    input.keypair,
  );

  const stats = fs.statSync(input.outputPath);
  return {
    pdfPath: input.outputPath,
    pdfSizeBytes: stats.size,
    pageCount: 1 + input.pages.length + 1,
    sealed: sealResult.sealed,
    signatureFingerprint: sealResult.fingerprint,
    signedAt: sealResult.signedAt,
    warnings: [...warnings, ...sealResult.warnings],
  };
}

function drawLevelingCertPage(doc: PDFKit.PDFDocument, input: LevelingBookInput) {
  const yStart = MARGIN_PT + 30;
  doc.font('Helvetica-Bold').fontSize(FS_TITLE + 2).fillColor(COLOR_ACCENT)
    .text("SURVEYOR'S CERTIFICATE — LEVELING", MARGIN_PT, yStart, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  doc.font('Helvetica-Oblique').fontSize(FS_SUBHEADING).fillColor(COLOR_GREY)
    .text('Survey Regulations 1994, Regulation 3(2) — RDM 1.1 Section 5',
      MARGIN_PT, yStart + 22, { align: 'center', width: A4_WIDTH_PT - 2 * MARGIN_PT });

  let y = yStart + 50;
  const c = input.closure;
  const body = [
    `I, ${input.surveyor.name} (Licensed Surveyor No. ${input.surveyor.license}),`,
    `hereby certify that the leveling survey described in this book was`,
    `executed by me (or under my immediate personal supervision) on`,
    `${input.project.surveyDate}, in accordance with the Survey Act (Cap. 299)`,
    `and the Road Design Manual RDM 1.1 (2025).`,
    '',
    `Leveling particulars:`,
    `  Project:           ${input.project.name}`,
    `  Locality:          ${input.project.locality}, ${input.project.county} County`,
    `  Level:             ${input.project.levelType} (S/N ${input.project.levelSerial})`,
    `  Staff:             ${input.project.staffType} (S/N ${input.project.staffSerial})`,
    `  Total pages:       ${input.pages.length}`,
    c ? `  Total distance:    ${fmtDistance(c.totalDistance)} m` : '',
    c ? `  Number of setups: ${c.numberOfSetups}` : '',
    c ? `  Misclosure:        ${c.misclosure.toFixed(2)} mm` : '',
    c ? `  Allowable:         ${c.allowable.toFixed(2)} mm (${c.closureStandard})` : '',
    c ? `  Result:            ${c.passes ? 'PASS' : 'FAIL'}` : '',
    c ? `  Precision class:   ${c.precisionClass}` : '',
    '',
    `I further certify that:`,
    `  (a) The instrument was checked for collimation error before work commenced;`,
    `  (b) All readings were taken with the staff vertical using a staff bubble;`,
    `  (c) Equal foresight and backsight distances were maintained;`,
    `  (d) All page checks were satisfied before leaving the field;`,
    `  (e) The closure meets the standard stated above.`,
  ];
  for (const line of body) {
    doc.font('Helvetica').fontSize(FS_BODY).fillColor(COLOR_BLACK)
      .text(line, MARGIN_PT, y, { width: A4_WIDTH_PT - 2 * MARGIN_PT });
    y += 13;
  }
}
