#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PyQGIS loader script — generated by metardu-desktop.

This script loads metardu-desktop's survey data into QGIS with
country-correct symbology. Run it from the QGIS Python console
(Plugins → Python Console → Open Console → click the folder icon
→ select this .py file).

# Project metadata

  Project name:        Golden Fixture — Kenya Topographic PyQGIS
  Surveyor:            Jane Wanjiru
  License number:      LS/1234
  Survey date:         2026-07-23
  Adjustment run ID:   golden-pyqgis-topo-ke-001
  Country code:        KE
  Survey type:         topographic
  CRS:                 urn:ogc:def:crs:EPSG::21037 (EPSG:21037)
  Generated:           2026-07-22T22:39:34.235Z
  Generator:           metardu-desktop PyQGIS script generator v1.0.0

# Survey-type summary

{
  "topographic": {
    "triangleCount": 64,
    "minElevation": 100,
    "maxElevation": 120,
    "meanSlope": 26.565051177077937,
    "contourCount": 64,
    "spotHeightCount": 3
  }
}

# What this script does

  1. Sets the QGIS canvas CRS to EPSG:21037 (the survey's CRS —
     sourced from country-config, never hardcoded).
  2. Loads each survey layer from the GeoPackage file located at:
       metardu-survey.gpkg
  3. Applies country-correct symbology per the survey type and country.
  4. Groups all layers under a project-named tree node in the Layers panel.
  5. Zooms the canvas to the combined layer extent.

# Architectural notes

  - Per-feature uncertainty (semi_major, semi_minor, orientation columns
    in the GeoPackage) is referenced by name in the symbology code so
    the analyst can data-define symbol size by uncertainty.
  - Cross-section profiles (engineering surveys) are in (offset, cut-fill-
    depth) space, NOT map (E, N) space. They render as garbage on a map
    canvas — they're meant for CAD/profile-chart tools. The script loads
    them but flags them in red so the analyst knows to treat them as
    non-map features.
  - This script does NOT modify the GeoPackage. Re-running it loads
    the layers again. To clean up: close QGIS without saving the project,
    or remove the layers manually.

# References

  - ADR-0005: docs/decisions/0005-integration-export-workflow-family.md
  - PyQGIS Cookbook: https://docs.qgis.org/3.34/en/docs/pyqgis_developer_cookbook/
"""

# Standard library imports.
import os
from datetime import datetime

# PyQGIS imports — only available inside a running QGIS Python console.
from qgis.core import (
    QgsProject,
    QgsVectorLayer,
    QgsCoordinateReferenceSystem,
    QgsProperty,
    QgsSingleSymbolRenderer,
    QgsMarkerSymbol,
    QgsLineSymbol,
    QgsFillSymbol,
    QgsUnitTypes,
    QgsPalLayerSettings,
    QgsVectorLayerSimpleLabeling,
)
from qgis.PyQt.QtGui import QColor
from qgis.PyQt.QtCore import Qt

# ─── Configuration ────────────────────────────────────────────────

GPKG_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "metardu-survey.gpkg"
)
GROUP_NAME = "Golden Fixture — Kenya Topographic PyQGIS"
SRID = 21037
CRS_URN = "urn:ogc:def:crs:EPSG::21037"

print(f"=" * 60)
print(f"metardu-desktop PyQGIS loader — {GROUP_NAME}")
print(f"=" * 60)
print(f"GeoPackage path: {GPKG_PATH}")
print(f"CRS: {CRS_URN} (EPSG:{SRID})")
print(f"Generated: 2026-07-22T22:39:34.235Z")
print()

if not os.path.exists(GPKG_PATH):
    raise FileNotFoundError(
        f"GeoPackage file not found at: {{GPKG_PATH}}\n"
        f"Place the .gpkg file (exported from metardu-desktop) next to "
        f"this .py file, or edit GPKG_PATH above to point to it."
    )

# ─── Set canvas CRS to the survey's CRS ───────────────────────────

crs = QgsCoordinateReferenceSystem(f"EPSG:{SRID}")
if not crs.isValid():
    raise ValueError(f"Invalid EPSG code: {SRID}")
QgsProject.instance().setCrs(crs)
print(f"Canvas CRS set to EPSG:{SRID}")

# ─── Create the layer-tree group ──────────────────────────────────

root = QgsProject.instance().layerTreeRoot()
# Remove any existing group with the same name (idempotent re-runs).
existing = root.findGroup(GROUP_NAME)
if existing is not None:
    root.removeChildNode(existing)
project_group = root.insertGroup(0, GROUP_NAME)

# ─── Load each layer ──────────────────────────────────────────────

# ─── Layer 1: Topo Points (TIN Vertices) ──────────────────
layer_0 = QgsVectorLayer(
    "metardu-survey.gpkg|layername=topo_points",
    "Topo Points (TIN Vertices)",
    "ogr"
)
if not layer_0.isValid():
    print("WARNING: layer 'topo_points' failed to load from metardu-survey.gpkg")
else:
    # Apply country-correct symbology per ADR-0005 Brief 04.
    vlayer = layer_0
    # Topo points: small gray dots, scaled by uncertainty if present.
    sym = QgsMarkerSymbol.createSimple({})
    sym.setSizeUnit(QgsUnitTypes.RenderMillimeters)
    sym.setSize(0.8)
    sym.setColor(QColor(120, 120, 120))
    vlayer.setRenderer(QgsSingleSymbolRenderer(sym))
    # Label topo points with their point_id (off by default — too many points).
    # Analyst can toggle on in QGIS layer properties.
    labels = QgsPalLayerSettings()
    labels.fieldName = 'point_id'
    labels.enabled = False
    vlayer.setLabeling(QgsVectorLayerSimpleLabeling(labels))
    # Add to the project group.
    QgsProject.instance().addMapLayer(layer_0, False)
    group_0 = root.addChildGroup("Topo Points (TIN Vertices)")
    group_0.addLayer(layer_0)
    print(f"Loaded layer: Topo Points (TIN Vertices) (" + str(layer_0.featureCount()) + " features)")

# ─── Layer 2: Contours ──────────────────
layer_1 = QgsVectorLayer(
    "metardu-survey.gpkg|layername=contours",
    "Contours",
    "ogr"
)
if not layer_1.isValid():
    print("WARNING: layer 'contours' failed to load from metardu-survey.gpkg")
else:
    # Apply country-correct symbology per ADR-0005 Brief 04.
    vlayer = layer_1
    # Contours: brown lines. Use graduated renderer by elevation so
    # major contours (every 5m or 10m) can be thicker than minor ones.
    sym = QgsLineSymbol.createSimple({})
    sym.setColor(QColor(139, 69, 19))  # brown
    sym.setWidth(0.25)
    vlayer.setRenderer(QgsSingleSymbolRenderer(sym))
    # Graduated by elevation modulo contour interval — left as an exercise
    # for the analyst; the field is named 'elevation'.
    # Label contours with their elevation.
    labels = QgsPalLayerSettings()
    labels.fieldName = 'elevation'
    labels.enabled = True
    labels.decimals = 1
    labels.formatNumbers = True
    vlayer.setLabeling(QgsVectorLayerSimpleLabeling(labels))
    # Add to the project group.
    QgsProject.instance().addMapLayer(layer_1, False)
    group_1 = root.addChildGroup("Contours")
    group_1.addLayer(layer_1)
    print(f"Loaded layer: Contours (" + str(layer_1.featureCount()) + " features)")

# ─── Layer 3: Spot Heights ──────────────────
layer_2 = QgsVectorLayer(
    "metardu-survey.gpkg|layername=spot_heights",
    "Spot Heights",
    "ogr"
)
if not layer_2.isValid():
    print("WARNING: layer 'spot_heights' failed to load from metardu-survey.gpkg")
else:
    # Apply country-correct symbology per ADR-0005 Brief 04.
    vlayer = layer_2
    # Spot heights: green dots, slightly larger than topo points.
    sym = QgsMarkerSymbol.createSimple({})
    sym.setSizeUnit(QgsUnitTypes.RenderMillimeters)
    sym.setSize(1.5)
    sym.setColor(QColor(0, 128, 0))
    vlayer.setRenderer(QgsSingleSymbolRenderer(sym))
    # Label spot heights with elevation.
    labels = QgsPalLayerSettings()
    labels.fieldName = 'elevation'
    labels.enabled = True
    labels.decimals = 2
    labels.formatNumbers = True
    vlayer.setLabeling(QgsVectorLayerSimpleLabeling(labels))
    # Add to the project group.
    QgsProject.instance().addMapLayer(layer_2, False)
    group_2 = root.addChildGroup("Spot Heights")
    group_2.addLayer(layer_2)
    print(f"Loaded layer: Spot Heights (" + str(layer_2.featureCount()) + " features)")

# ─── Zoom to the combined layer extent ────────────────────────────

# Get the extent of all added layers and set the canvas to it.
canvas = iface.mapCanvas()
extents = []
for layer in QgsProject.instance().mapLayers().values():
    if layer.name().startswith("Beacon") or \
       layer.name().startswith("Parcel") or \
       layer.name().startswith("Topo") or \
       layer.name().startswith("Contour") or \
       layer.name().startswith("Spot") or \
       layer.name().startswith("Section"):
        try:
            extents.append(layer.extent())
        except Exception:
            pass

if extents:
    combined = extents[0]
    for ext in extents[1:]:
        combined.combineExtentWith(ext)
    canvas.setExtent(combined)
    canvas.refresh()
    print(f"Canvas zoomed to combined extent: {combined.toString()}")

print()
print(f"=" * 60)
print(f"Loaded {len([l for l in QgsProject.instance().mapLayers().values() if GROUP_NAME in (l.name() or '')])} layers under group '{GROUP_NAME}'")
print(f"=" * 60)
print(f"Done. Inspect the Layers panel — your metardu-desktop survey")
print(f"layers are grouped under '{GROUP_NAME}'.")
print()
print(f"Tip: per-feature uncertainty columns (semi_major, semi_minor,")
print(f"orientation) are available for data-defined symbology. Right-click")
print(f"a layer → Properties → Symbology → Data-defined override.")
