/**
 * METARDU — PDF Digital Signature Engine
 *
 * Embeds professional digital signature appearance blocks into existing PDFs
 * using pdf-lib. Works with PDFs generated by any source (jsPDF, svg2pdf, etc.)
 * by operating on the raw bytes.
 *
 * @module pdfDigitalSignature
 */

import {
  PDFDocument,
  rgb,
  StandardFonts,
} from 'pdf-lib';
import QRCode from 'qrcode';

// ---------------------------------------------------------------------------
// Exported types
// ---------------------------------------------------------------------------

/**
 * Data required to render the signature appearance on a PDF page.
 */
export interface SignatureAppearanceData {
  /** Full name of the licensed surveyor */
  surveyorName: string;
  /** Institution of Surveyors of Kenya registration number */
  iskNumber: string;
  /** Registered firm / company name */
  firmName: string;
  /** ISO-8601 timestamp of when the signature was applied */
  signedAt: string;
  /** SHA-256 hex digest of the original document content */
  documentHash: string;
  /** Short opaque token used for public verification look-ups */
  verificationToken: string;
  /** How the signature was captured */
  method: 'DRAWN' | 'TYPED' | 'CERTIFICATE';
  /** Full verification URL (defaults to metardu.co.ke if omitted) */
  verificationUrl?: string;
}

/**
 * Subset of a DB `document_signatures` row needed to embed a signature.
 */
export interface SignatureRecord {
  documentHash: string;
  surveyorName: string;
  iskNumber: string;
  firmName: string;
  signedAt: string;
  verificationToken: string;
  method: 'DRAWN' | 'TYPED' | 'CERTIFICATE';
}

// ---------------------------------------------------------------------------
// Layout constants
// ---------------------------------------------------------------------------

/** Block width in PDF points */
const BLOCK_WIDTH = 200;
/** Block height in PDF points (increased slightly to accommodate QR row) */
const BLOCK_HEIGHT = 85;

/** Background fill colour */
const BG_COLOR = rgb(0.922, 0.961, 0.984); // #EBF5FB
/** Border stroke colour */
const BORDER_COLOR = rgb(0.106, 0.227, 0.361); // #1B3A5C

/** Text colours */
const HEADER_COLOR = rgb(0.106, 0.227, 0.361); // #1B3A5C
const BODY_COLOR = rgb(0.15, 0.15, 0.15); // #262626
const MUTED_COLOR = rgb(0.45, 0.45, 0.45); // #737373

/** Internal padding from block edges */
const PADDING = 8;
/** QR code image size (width & height in pt) */
const QR_SIZE = 48;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert a QR code data-URL string (`data:image/png;base64,…`) into raw
 * `Uint8Array` PNG bytes that pdf-lib can embed.
 */
export function generateQrCodePng(dataUrl: string): Uint8Array {
  const base64 = dataUrl.replace(/^data:image\/png;base64,/, '');
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

/**
 * Build the default verification URL from a token.
 */
function buildVerificationUrl(token: string): string {
  return `https://metardu.co.ke/verify?token=${token.toUpperCase()}`;
}

/**
 * Format an ISO date string as DD/MM/YYYY.
 */
function formatDate(iso: string): string {
  const d = new Date(iso);
  const dd = String(d.getUTCDate()).padStart(2, '0');
  const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
  const yyyy = d.getUTCFullYear();
  return `${dd}/${mm}/${yyyy}`;
}

/**
 * Clamp a number between a minimum and maximum value.
 */
function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

/**
 * Truncate a string to `maxLength` characters and append "…" if needed.
 */
function truncate(str: string, maxLength: number): string {
  if (str.length <= maxLength) return str;
  return `${str.slice(0, maxLength)}…`;
}

// ---------------------------------------------------------------------------
// Core: embedSignatureAppearance
// ---------------------------------------------------------------------------

/**
 * Embed a professional digital-signature appearance block on the **last page**
 * of an existing PDF.
 *
 * The block is drawn at the bottom-centre of the page and contains the
 * surveyor's identity, signing metadata, document hash, a verification QR
 * code, and the signature method indicator.
 *
 * @param pdfBytes  - Raw bytes of the source PDF (will not be mutated).
 * @param signature - Signature metadata to render.
 * @returns A new `Uint8Array` containing the signed PDF.
 *
 * @example
 * ```ts
 * const signedPdf = await embedSignatureAppearance(originalBytes, {
 *   surveyorName: 'Jane Wanjiru',
 *   iskNumber: 'ISK-1234',
 *   firmName: 'GeoSurveys Ltd',
 *   signedAt: new Date().toISOString(),
 *   documentHash: 'abc123…',
 *   verificationToken: 'X7K9M2P4Q1',
 *   method: 'DRAWN',
 * });
 * ```
 */
export async function embedSignatureAppearance(
  pdfBytes: Uint8Array,
  signature: SignatureAppearanceData,
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.load(pdfBytes, { ignoreEncryption: true });

  const pages = pdfDoc.getPages();
  if (pages.length === 0) {
    throw new Error('PDF contains no pages — cannot embed signature.');
  }

  const page = pages[pages.length - 1];
  const { width: pageWidth, height: pageHeight } = page.getSize();

  // ------------------------------------------------------------------
  // Load fonts
  // ------------------------------------------------------------------
  const fontRegular = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const fontMono = await pdfDoc.embedFont(StandardFonts.Courier);

  // ------------------------------------------------------------------
  // Calculate block position (bottom-centre, 20pt margin from edges)
  // ------------------------------------------------------------------
  const margin = 20;
  const x = clamp((pageWidth - BLOCK_WIDTH) / 2, margin, pageWidth - BLOCK_WIDTH - margin);
  const y = clamp(margin, margin, pageHeight - BLOCK_HEIGHT - margin);

  // ------------------------------------------------------------------
  // Draw background rectangle
  // ------------------------------------------------------------------
  page.drawRectangle({
    x,
    y,
    width: BLOCK_WIDTH,
    height: BLOCK_HEIGHT,
    color: BG_COLOR,
    borderColor: BORDER_COLOR,
    borderWidth: 1.2,
  });

  // ------------------------------------------------------------------
  // Draw "DIGITALLY SIGNED" header
  // ------------------------------------------------------------------
  page.drawText('DIGITALLY SIGNED', {
    x: x + PADDING,
    y: y + BLOCK_HEIGHT - 14,
    size: 8,
    font: fontBold,
    color: HEADER_COLOR,
  });

  // Underline beneath header
  page.drawLine({
    start: { x: x + PADDING, y: y + BLOCK_HEIGHT - 17 },
    end: { x: x + BLOCK_WIDTH - PADDING, y: y + BLOCK_HEIGHT - 17 },
    thickness: 0.5,
    color: BORDER_COLOR,
  });

  // ------------------------------------------------------------------
  // Text column (left side of block)
  // ------------------------------------------------------------------
  const textX = x + PADDING;
  const bodySize = 6.5;
  const lineHeight = 9;
  let textY = y + BLOCK_HEIGHT - 28;

  // Surveyor name (bold)
  page.drawText(truncate(signature.surveyorName, 30), {
    x: textX,
    y: textY,
    size: bodySize + 0.5,
    font: fontBold,
    color: BODY_COLOR,
  });
  textY -= lineHeight;

  // ISK number
  if (signature.iskNumber) {
    page.drawText(`ISK: ${signature.iskNumber}`, {
      x: textX,
      y: textY,
      size: bodySize,
      font: fontRegular,
      color: BODY_COLOR,
    });
    textY -= lineHeight;
  }

  // Firm name
  if (signature.firmName) {
    page.drawText(truncate(signature.firmName, 32), {
      x: textX,
      y: textY,
      size: bodySize,
      font: fontRegular,
      color: BODY_COLOR,
    });
    textY -= lineHeight;
  }

  // Date signed
  page.drawText(`Date: ${formatDate(signature.signedAt)}`, {
    x: textX,
    y: textY,
    size: bodySize,
    font: fontRegular,
    color: BODY_COLOR,
  });
  textY -= lineHeight;

  // Method indicator
  page.drawText(`Method: ${signature.method}`, {
    x: textX,
    y: textY,
    size: bodySize,
    font: fontRegular,
    color: MUTED_COLOR,
  });

  // ------------------------------------------------------------------
  // Hash & verification token (below main text column)
  // ------------------------------------------------------------------
  const hashY = y + PADDING + 2;
  const shortHash = signature.documentHash.slice(0, 16).toUpperCase();
  page.drawText(`Hash: ${shortHash}`, {
    x: textX,
    y: hashY,
    size: 5.5,
    font: fontMono,
    color: MUTED_COLOR,
  });

  const tokenText = `Token: ${signature.verificationToken.toUpperCase().slice(0, 12)}`;
  page.drawText(tokenText, {
    x: textX,
    y: hashY - 7.5,
    size: 5.5,
    font: fontMono,
    color: MUTED_COLOR,
  });

  // ------------------------------------------------------------------
  // QR code (right side of block)
  // ------------------------------------------------------------------
  const verificationUrl = signature.verificationUrl ?? buildVerificationUrl(signature.verificationToken);
  let qrEmbedded = false;

  try {
    const qrDataUrl = await QRCode.toDataURL(verificationUrl, {
      width: 160,          // pixels — gives decent resolution for print
      margin: 1,
      color: { dark: '#1B3A5C', light: '#EBF5FB' },
      errorCorrectionLevel: 'M',
    });
    const qrPngBytes = generateQrCodePng(qrDataUrl);
    const qrImage = await pdfDoc.embedPng(qrPngBytes);

    // Position QR in top-right corner of the signature block
    const qrX = x + BLOCK_WIDTH - QR_SIZE - PADDING;
    const qrY = y + BLOCK_HEIGHT - QR_SIZE - 12;

    page.drawImage(qrImage, {
      x: qrX,
      y: qrY,
      width: QR_SIZE,
      height: QR_SIZE,
    });
    qrEmbedded = true;
  } catch {
    // QR generation failed — fall through to text-only fallback
  }

  // ------------------------------------------------------------------
  // Fallback: if QR embedding failed, show verification URL as text
  // ------------------------------------------------------------------
  if (!qrEmbedded) {
    const urlText = truncate(verificationUrl, 42);
    page.drawText(urlText, {
      x: x + BLOCK_WIDTH - PADDING - fontMono.widthOfTextAtSize(urlText, 5),
      y: y + BLOCK_HEIGHT - 35,
      size: 5,
      font: fontMono,
      color: MUTED_COLOR,
    });
    page.drawText('Verify at:', {
      x: x + BLOCK_WIDTH - PADDING - fontRegular.widthOfTextAtSize('Verify at:', 5.5),
      y: y + BLOCK_HEIGHT - 28,
      size: 5.5,
      font: fontRegular,
      color: MUTED_COLOR,
    });
  } else {
    // Small "Scan to verify" label below QR
    const verifyLabel = 'Scan to verify';
    const verifyLabelWidth = fontRegular.widthOfTextAtSize(verifyLabel, 5);
    page.drawText(verifyLabel, {
      x: x + BLOCK_WIDTH - PADDING - (QR_SIZE / 2) - (verifyLabelWidth / 2),
      y: y + 10,
      size: 5,
      font: fontRegular,
      color: MUTED_COLOR,
    });
  }

  // ------------------------------------------------------------------
  // Save and return
  // ------------------------------------------------------------------
  return pdfDoc.save();
}

// ---------------------------------------------------------------------------
// Convenience: signPdfDocument
// ---------------------------------------------------------------------------

/**
 * High-level convenience function that combines **hash verification** with
 * signature embedding.
 *
 * It checks that `signatureRecord.documentHash` matches the SHA-256 digest of
 * `pdfBytes`. If the hashes diverge the document has been tampered with and
 * the function throws rather than embedding an invalid signature.
 *
 * @param pdfBytes         - Raw bytes of the PDF to sign.
 * @param signatureRecord  - The database signature record (must include the
 *                           original `documentHash`).
 * @returns Signed PDF bytes.
 * @throws {Error} If the document hash does not match the record.
 */
export async function signPdfDocument(
  pdfBytes: Uint8Array,
  signatureRecord: SignatureRecord,
): Promise<Uint8Array> {
  // Lazy-import the hashing utility to keep this module's bundle lean when
  // only the appearance functions are needed.
  const { hashDocument } = await import('./digitalSignature');

  // hashDocument expects a string, so convert bytes to base64
  const pdfBase64 = Buffer.from(pdfBytes).toString('base64');
  const currentHash = hashDocument(pdfBase64);
  if (currentHash !== signatureRecord.documentHash) {
    throw new Error(
      'Document hash mismatch — the file has been modified since it was ' +
      'prepared for signing. Refusing to embed signature.',
    );
  }

  const appearanceData: SignatureAppearanceData = {
    surveyorName: signatureRecord.surveyorName,
    iskNumber: signatureRecord.iskNumber,
    firmName: signatureRecord.firmName,
    signedAt: signatureRecord.signedAt,
    documentHash: signatureRecord.documentHash,
    verificationToken: signatureRecord.verificationToken,
    method: signatureRecord.method,
  };

  return embedSignatureAppearance(pdfBytes, appearanceData);
}
