/**
 * Generic KML mission export.
 *
 * Generates a KML 2.2 file with Point geometry for each waypoint and
 * ExtendedData elements for altitude, speed, and action metadata.
 *
 * This format is importable by Google Earth, QGIS, ArcGIS, and any other
 * GIS application that supports KML. It does NOT support direct upload to
 * a drone — it's a universal exchange format.
 *
 * Reference: https://developers.google.com/kml/documentation/kmlreference
 */

import type { Waypoint } from "../waypoints.js";

export interface KmlOptions {
  /**
   * Mission name (shown in Google Earth as the folder name).
   * Default: "MetaRDU Mission".
   */
  missionName?: string;
  /**
   * Description text for the KML folder.
   */
  description?: string;
  /**
   * Whether to draw a LineString connecting the waypoints (flight path).
   * Default: true.
   */
  drawFlightPath?: boolean;
  /**
   * Color of the flight path line in KML hex format (aabbggrr).
   * Default: ffff7800 (orange, 100% opacity).
   */
  pathColor?: string;
  /**
   * Width of the flight path line in pixels. Default: 2.
   */
  pathWidth?: number;
}

/**
 * Generate generic KML content as a string.
 */
export function exportKml(
  waypoints: Waypoint[],
  options: KmlOptions = {}
): string {
  if (waypoints.length === 0) {
    throw new Error("Cannot export KML: waypoints array is empty");
  }

  const missionName = options.missionName ?? "MetaRDU Mission";
  const description = options.description ?? `Generated by MetaRDU Desktop v2.0 — ${waypoints.length} waypoints`;
  const drawPath = options.drawFlightPath ?? true;
  const pathColor = options.pathColor ?? "ffff7800";
  const pathWidth = options.pathWidth ?? 2;

  // Build placemark XML for each waypoint
  const placemarks = waypoints.map((wp, i) => {
    const heading = wp.headingDegrees ?? 0;
    const speed = wp.speedMs ?? 0;
    const gimbalPitch = wp.gimbalPitchDegrees ?? 0;
    return `    <Placemark>
      <name>WP ${i + 1}</name>
      <description>Waypoint ${i + 1} of ${waypoints.length}
Flight line: ${wp.flightLine + 1}
Altitude: ${wp.altitudeMeters.toFixed(2)} m AGL
Heading: ${heading.toFixed(1)}°
Photo: ${wp.isPhoto ? "Yes" : "No"}</description>
      <Point>
        <coordinates>${wp.longitude.toFixed(8)},${wp.latitude.toFixed(8)},${wp.altitudeMeters.toFixed(2)}</coordinates>
        <altitudeMode>relativeToGround</altitudeMode>
      </Point>
      <ExtendedData>
        <Data name="index"><value>${wp.index}</value></Data>
        <Data name="flightLine"><value>${wp.flightLine}</value></Data>
        <Data name="altitudeMeters"><value>${wp.altitudeMeters.toFixed(2)}</value></Data>
        <Data name="headingDegrees"><value>${heading.toFixed(2)}</value></Data>
        <Data name="speedMs"><value>${speed.toFixed(2)}</value></Data>
        <Data name="gimbalPitchDegrees"><value>${gimbalPitch.toFixed(0)}</value></Data>
        <Data name="isPhoto"><value>${wp.isPhoto}</value></Data>
      </ExtendedData>
    </Placemark>`;
  }).join("\n");

  // Optional flight path LineString
  const flightPathXml = drawPath
    ? `
    <Placemark>
      <name>Flight Path</name>
      <Style>
        <LineStyle>
          <color>${pathColor}</color>
          <width>${pathWidth}</width>
        </LineStyle>
      </Style>
      <LineString>
        <tessellate>1</tessellate>
        <altitudeMode>relativeToGround</altitudeMode>
        <coordinates>
${waypoints.map((wp) => `          ${wp.longitude.toFixed(8)},${wp.latitude.toFixed(8)},${wp.altitudeMeters.toFixed(2)}`).join("\n")}
        </coordinates>
      </LineString>
    </Placemark>`
    : "";

  return `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(missionName)}</name>
    <description>${escapeXml(description)}</description>
    <Folder>
      <name>Waypoints</name>
${placemarks}
    </Folder>
${flightPathXml}
  </Document>
</kml>
`;
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
